// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/TokenFlux/TokenRouter/ent/group"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
	"github.com/TokenFlux/TokenRouter/ent/provider"
	"github.com/TokenFlux/TokenRouter/ent/providergroup"
)

// ProviderGroupQuery is the builder for querying ProviderGroup entities.
type ProviderGroupQuery struct {
	config
	ctx          *QueryContext
	order        []providergroup.OrderOption
	inters       []Interceptor
	predicates   []predicate.ProviderGroup
	withProvider *ProviderQuery
	withGroup    *GroupQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProviderGroupQuery builder.
func (_q *ProviderGroupQuery) Where(ps ...predicate.ProviderGroup) *ProviderGroupQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ProviderGroupQuery) Limit(limit int) *ProviderGroupQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ProviderGroupQuery) Offset(offset int) *ProviderGroupQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ProviderGroupQuery) Unique(unique bool) *ProviderGroupQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ProviderGroupQuery) Order(o ...providergroup.OrderOption) *ProviderGroupQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProvider chains the current query on the "provider" edge.
func (_q *ProviderGroupQuery) QueryProvider() *ProviderQuery {
	query := (&ProviderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(providergroup.Table, providergroup.ProviderColumn, selector),
			sqlgraph.To(provider.Table, provider.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, providergroup.ProviderTable, providergroup.ProviderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (_q *ProviderGroupQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(providergroup.Table, providergroup.GroupColumn, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, providergroup.GroupTable, providergroup.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProviderGroup entity from the query.
// Returns a *NotFoundError when no ProviderGroup was found.
func (_q *ProviderGroupQuery) First(ctx context.Context) (*ProviderGroup, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{providergroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ProviderGroupQuery) FirstX(ctx context.Context) *ProviderGroup {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single ProviderGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProviderGroup entity is found.
// Returns a *NotFoundError when no ProviderGroup entities are found.
func (_q *ProviderGroupQuery) Only(ctx context.Context) (*ProviderGroup, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{providergroup.Label}
	default:
		return nil, &NotSingularError{providergroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ProviderGroupQuery) OnlyX(ctx context.Context) *ProviderGroup {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of ProviderGroups.
func (_q *ProviderGroupQuery) All(ctx context.Context) ([]*ProviderGroup, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProviderGroup, *ProviderGroupQuery]()
	return withInterceptors[[]*ProviderGroup](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ProviderGroupQuery) AllX(ctx context.Context) []*ProviderGroup {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (_q *ProviderGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ProviderGroupQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ProviderGroupQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ProviderGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ProviderGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProviderGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ProviderGroupQuery) Clone() *ProviderGroupQuery {
	if _q == nil {
		return nil
	}
	return &ProviderGroupQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]providergroup.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.ProviderGroup{}, _q.predicates...),
		withProvider: _q.withProvider.Clone(),
		withGroup:    _q.withGroup.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProvider tells the query-builder to eager-load the nodes that are connected to
// the "provider" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProviderGroupQuery) WithProvider(opts ...func(*ProviderQuery)) *ProviderGroupQuery {
	query := (&ProviderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProvider = query
	return _q
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProviderGroupQuery) WithGroup(opts ...func(*GroupQuery)) *ProviderGroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProviderID int64 `json:"provider_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProviderGroup.Query().
//		GroupBy(providergroup.FieldProviderID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ProviderGroupQuery) GroupBy(field string, fields ...string) *ProviderGroupGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProviderGroupGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = providergroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProviderID int64 `json:"provider_id,omitempty"`
//	}
//
//	client.ProviderGroup.Query().
//		Select(providergroup.FieldProviderID).
//		Scan(ctx, &v)
func (_q *ProviderGroupQuery) Select(fields ...string) *ProviderGroupSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ProviderGroupSelect{ProviderGroupQuery: _q}
	sbuild.label = providergroup.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProviderGroupSelect configured with the given aggregations.
func (_q *ProviderGroupQuery) Aggregate(fns ...AggregateFunc) *ProviderGroupSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ProviderGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !providergroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ProviderGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProviderGroup, error) {
	var (
		nodes       = []*ProviderGroup{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withProvider != nil,
			_q.withGroup != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProviderGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProviderGroup{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProvider; query != nil {
		if err := _q.loadProvider(ctx, query, nodes, nil,
			func(n *ProviderGroup, e *Provider) { n.Edges.Provider = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *ProviderGroup, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ProviderGroupQuery) loadProvider(ctx context.Context, query *ProviderQuery, nodes []*ProviderGroup, init func(*ProviderGroup), assign func(*ProviderGroup, *Provider)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ProviderGroup)
	for i := range nodes {
		fk := nodes[i].ProviderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(provider.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "provider_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProviderGroupQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*ProviderGroup, init func(*ProviderGroup), assign func(*ProviderGroup, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ProviderGroup)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ProviderGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ProviderGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(providergroup.Table, providergroup.Columns, nil)
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if _q.withProvider != nil {
			_spec.Node.AddColumnOnce(providergroup.FieldProviderID)
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(providergroup.FieldGroupID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ProviderGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(providergroup.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = providergroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ProviderGroupQuery) ForUpdate(opts ...sql.LockOption) *ProviderGroupQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ProviderGroupQuery) ForShare(opts ...sql.LockOption) *ProviderGroupQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ProviderGroupGroupBy is the group-by builder for ProviderGroup entities.
type ProviderGroupGroupBy struct {
	selector
	build *ProviderGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ProviderGroupGroupBy) Aggregate(fns ...AggregateFunc) *ProviderGroupGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ProviderGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProviderGroupQuery, *ProviderGroupGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ProviderGroupGroupBy) sqlScan(ctx context.Context, root *ProviderGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProviderGroupSelect is the builder for selecting fields of ProviderGroup entities.
type ProviderGroupSelect struct {
	*ProviderGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ProviderGroupSelect) Aggregate(fns ...AggregateFunc) *ProviderGroupSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ProviderGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProviderGroupQuery, *ProviderGroupSelect](ctx, _s.ProviderGroupQuery, _s, _s.inters, v)
}

func (_s *ProviderGroupSelect) sqlScan(ctx context.Context, root *ProviderGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
