// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/TokenFlux/TokenRouter/ent/group"
	"github.com/TokenFlux/TokenRouter/ent/provider"
	"github.com/TokenFlux/TokenRouter/ent/providergroup"
)

// ProviderGroup is the model entity for the ProviderGroup schema.
type ProviderGroup struct {
	config `json:"-"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID int64 `json:"provider_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProviderGroupQuery when eager-loading is set.
	Edges        ProviderGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProviderGroupEdges holds the relations/edges for other nodes in the graph.
type ProviderGroupEdges struct {
	// Provider holds the value of the provider edge.
	Provider *Provider `json:"provider,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProviderGroupEdges) ProviderOrErr() (*Provider, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: provider.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProviderGroupEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providergroup.FieldProviderID, providergroup.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case providergroup.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderGroup fields.
func (_m *ProviderGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providergroup.FieldProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = value.Int64
			}
		case providergroup.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case providergroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderGroup.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProvider queries the "provider" edge of the ProviderGroup entity.
func (_m *ProviderGroup) QueryProvider() *ProviderQuery {
	return NewProviderGroupClient(_m.config).QueryProvider(_m)
}

// QueryGroup queries the "group" edge of the ProviderGroup entity.
func (_m *ProviderGroup) QueryGroup() *GroupQuery {
	return NewProviderGroupClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this ProviderGroup.
// Note that you need to call ProviderGroup.Unwrap() before calling this method if this ProviderGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderGroup) Update() *ProviderGroupUpdateOne {
	return NewProviderGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderGroup) Unwrap() *ProviderGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderGroup) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderGroup(")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderGroups is a parsable slice of ProviderGroup.
type ProviderGroups []*ProviderGroup
