// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TokenFlux/TokenRouter/ent/group"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
	"github.com/TokenFlux/TokenRouter/ent/provider"
	"github.com/TokenFlux/TokenRouter/ent/providergroup"
)

// ProviderGroupUpdate is the builder for updating ProviderGroup entities.
type ProviderGroupUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderGroupMutation
}

// Where appends a list predicates to the ProviderGroupUpdate builder.
func (_u *ProviderGroupUpdate) Where(ps ...predicate.ProviderGroup) *ProviderGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *ProviderGroupUpdate) SetProviderID(v int64) *ProviderGroupUpdate {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *ProviderGroupUpdate) SetNillableProviderID(v *int64) *ProviderGroupUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ProviderGroupUpdate) SetGroupID(v int64) *ProviderGroupUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ProviderGroupUpdate) SetNillableGroupID(v *int64) *ProviderGroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetProvider sets the "provider" edge to the Provider entity.
func (_u *ProviderGroupUpdate) SetProvider(v *Provider) *ProviderGroupUpdate {
	return _u.SetProviderID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *ProviderGroupUpdate) SetGroup(v *Group) *ProviderGroupUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the ProviderGroupMutation object of the builder.
func (_u *ProviderGroupUpdate) Mutation() *ProviderGroupMutation {
	return _u.mutation
}

// ClearProvider clears the "provider" edge to the Provider entity.
func (_u *ProviderGroupUpdate) ClearProvider() *ProviderGroupUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *ProviderGroupUpdate) ClearGroup() *ProviderGroupUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderGroupUpdate) check() error {
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProviderGroup.provider"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProviderGroup.group"`)
	}
	return nil
}

func (_u *ProviderGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providergroup.Table, providergroup.Columns, sqlgraph.NewFieldSpec(providergroup.FieldProviderID, field.TypeInt64), sqlgraph.NewFieldSpec(providergroup.FieldGroupID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   providergroup.ProviderTable,
			Columns: []string{providergroup.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   providergroup.ProviderTable,
			Columns: []string{providergroup.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   providergroup.GroupTable,
			Columns: []string{providergroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   providergroup.GroupTable,
			Columns: []string{providergroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderGroupUpdateOne is the builder for updating a single ProviderGroup entity.
type ProviderGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderGroupMutation
}

// SetProviderID sets the "provider_id" field.
func (_u *ProviderGroupUpdateOne) SetProviderID(v int64) *ProviderGroupUpdateOne {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *ProviderGroupUpdateOne) SetNillableProviderID(v *int64) *ProviderGroupUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ProviderGroupUpdateOne) SetGroupID(v int64) *ProviderGroupUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ProviderGroupUpdateOne) SetNillableGroupID(v *int64) *ProviderGroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetProvider sets the "provider" edge to the Provider entity.
func (_u *ProviderGroupUpdateOne) SetProvider(v *Provider) *ProviderGroupUpdateOne {
	return _u.SetProviderID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *ProviderGroupUpdateOne) SetGroup(v *Group) *ProviderGroupUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the ProviderGroupMutation object of the builder.
func (_u *ProviderGroupUpdateOne) Mutation() *ProviderGroupMutation {
	return _u.mutation
}

// ClearProvider clears the "provider" edge to the Provider entity.
func (_u *ProviderGroupUpdateOne) ClearProvider() *ProviderGroupUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *ProviderGroupUpdateOne) ClearGroup() *ProviderGroupUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the ProviderGroupUpdate builder.
func (_u *ProviderGroupUpdateOne) Where(ps ...predicate.ProviderGroup) *ProviderGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderGroupUpdateOne) Select(field string, fields ...string) *ProviderGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderGroup entity.
func (_u *ProviderGroupUpdateOne) Save(ctx context.Context) (*ProviderGroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderGroupUpdateOne) SaveX(ctx context.Context) *ProviderGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderGroupUpdateOne) check() error {
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProviderGroup.provider"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProviderGroup.group"`)
	}
	return nil
}

func (_u *ProviderGroupUpdateOne) sqlSave(ctx context.Context) (_node *ProviderGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providergroup.Table, providergroup.Columns, sqlgraph.NewFieldSpec(providergroup.FieldProviderID, field.TypeInt64), sqlgraph.NewFieldSpec(providergroup.FieldGroupID, field.TypeInt64))
	if id, ok := _u.mutation.ProviderID(); !ok {
		return nil, &ValidationError{Name: "provider_id", err: errors.New(`ent: missing "ProviderGroup.provider_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.GroupID(); !ok {
		return nil, &ValidationError{Name: "group_id", err: errors.New(`ent: missing "ProviderGroup.group_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !providergroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   providergroup.ProviderTable,
			Columns: []string{providergroup.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   providergroup.ProviderTable,
			Columns: []string{providergroup.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   providergroup.GroupTable,
			Columns: []string{providergroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   providergroup.GroupTable,
			Columns: []string{providergroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProviderGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
