// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TokenFlux/TokenRouter/ent/group"
	"github.com/TokenFlux/TokenRouter/ent/provider"
	"github.com/TokenFlux/TokenRouter/ent/proxy"
	"github.com/TokenFlux/TokenRouter/ent/usagelog"
)

// ProviderCreate is the builder for creating a Provider entity.
type ProviderCreate struct {
	config
	mutation *ProviderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProviderCreate) SetCreatedAt(v time.Time) *ProviderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableCreatedAt(v *time.Time) *ProviderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProviderCreate) SetUpdatedAt(v time.Time) *ProviderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableUpdatedAt(v *time.Time) *ProviderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ProviderCreate) SetDeletedAt(v time.Time) *ProviderCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableDeletedAt(v *time.Time) *ProviderCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ProviderCreate) SetName(v string) *ProviderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *ProviderCreate) SetNotes(v string) *ProviderCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableNotes(v *string) *ProviderCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *ProviderCreate) SetPlatform(v string) *ProviderCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ProviderCreate) SetType(v string) *ProviderCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetCredentials sets the "credentials" field.
func (_c *ProviderCreate) SetCredentials(v map[string]interface{}) *ProviderCreate {
	_c.mutation.SetCredentials(v)
	return _c
}

// SetExtra sets the "extra" field.
func (_c *ProviderCreate) SetExtra(v map[string]interface{}) *ProviderCreate {
	_c.mutation.SetExtra(v)
	return _c
}

// SetProxyID sets the "proxy_id" field.
func (_c *ProviderCreate) SetProxyID(v int64) *ProviderCreate {
	_c.mutation.SetProxyID(v)
	return _c
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableProxyID(v *int64) *ProviderCreate {
	if v != nil {
		_c.SetProxyID(*v)
	}
	return _c
}

// SetProxyFallbackOriginID sets the "proxy_fallback_origin_id" field.
func (_c *ProviderCreate) SetProxyFallbackOriginID(v int64) *ProviderCreate {
	_c.mutation.SetProxyFallbackOriginID(v)
	return _c
}

// SetNillableProxyFallbackOriginID sets the "proxy_fallback_origin_id" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableProxyFallbackOriginID(v *int64) *ProviderCreate {
	if v != nil {
		_c.SetProxyFallbackOriginID(*v)
	}
	return _c
}

// SetConcurrency sets the "concurrency" field.
func (_c *ProviderCreate) SetConcurrency(v int) *ProviderCreate {
	_c.mutation.SetConcurrency(v)
	return _c
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableConcurrency(v *int) *ProviderCreate {
	if v != nil {
		_c.SetConcurrency(*v)
	}
	return _c
}

// SetLoadFactor sets the "load_factor" field.
func (_c *ProviderCreate) SetLoadFactor(v int) *ProviderCreate {
	_c.mutation.SetLoadFactor(v)
	return _c
}

// SetNillableLoadFactor sets the "load_factor" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableLoadFactor(v *int) *ProviderCreate {
	if v != nil {
		_c.SetLoadFactor(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *ProviderCreate) SetPriority(v int) *ProviderCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *ProviderCreate) SetNillablePriority(v *int) *ProviderCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_c *ProviderCreate) SetRateMultiplier(v float64) *ProviderCreate {
	_c.mutation.SetRateMultiplier(v)
	return _c
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableRateMultiplier(v *float64) *ProviderCreate {
	if v != nil {
		_c.SetRateMultiplier(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProviderCreate) SetStatus(v string) *ProviderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableStatus(v *string) *ProviderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *ProviderCreate) SetErrorMessage(v string) *ProviderCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableErrorMessage(v *string) *ProviderCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *ProviderCreate) SetLastUsedAt(v time.Time) *ProviderCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableLastUsedAt(v *time.Time) *ProviderCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ProviderCreate) SetExpiresAt(v time.Time) *ProviderCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableExpiresAt(v *time.Time) *ProviderCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetAutoPauseOnExpired sets the "auto_pause_on_expired" field.
func (_c *ProviderCreate) SetAutoPauseOnExpired(v bool) *ProviderCreate {
	_c.mutation.SetAutoPauseOnExpired(v)
	return _c
}

// SetNillableAutoPauseOnExpired sets the "auto_pause_on_expired" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableAutoPauseOnExpired(v *bool) *ProviderCreate {
	if v != nil {
		_c.SetAutoPauseOnExpired(*v)
	}
	return _c
}

// SetSchedulable sets the "schedulable" field.
func (_c *ProviderCreate) SetSchedulable(v bool) *ProviderCreate {
	_c.mutation.SetSchedulable(v)
	return _c
}

// SetNillableSchedulable sets the "schedulable" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableSchedulable(v *bool) *ProviderCreate {
	if v != nil {
		_c.SetSchedulable(*v)
	}
	return _c
}

// SetRateLimitedAt sets the "rate_limited_at" field.
func (_c *ProviderCreate) SetRateLimitedAt(v time.Time) *ProviderCreate {
	_c.mutation.SetRateLimitedAt(v)
	return _c
}

// SetNillableRateLimitedAt sets the "rate_limited_at" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableRateLimitedAt(v *time.Time) *ProviderCreate {
	if v != nil {
		_c.SetRateLimitedAt(*v)
	}
	return _c
}

// SetRateLimitResetAt sets the "rate_limit_reset_at" field.
func (_c *ProviderCreate) SetRateLimitResetAt(v time.Time) *ProviderCreate {
	_c.mutation.SetRateLimitResetAt(v)
	return _c
}

// SetNillableRateLimitResetAt sets the "rate_limit_reset_at" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableRateLimitResetAt(v *time.Time) *ProviderCreate {
	if v != nil {
		_c.SetRateLimitResetAt(*v)
	}
	return _c
}

// SetOverloadUntil sets the "overload_until" field.
func (_c *ProviderCreate) SetOverloadUntil(v time.Time) *ProviderCreate {
	_c.mutation.SetOverloadUntil(v)
	return _c
}

// SetNillableOverloadUntil sets the "overload_until" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableOverloadUntil(v *time.Time) *ProviderCreate {
	if v != nil {
		_c.SetOverloadUntil(*v)
	}
	return _c
}

// SetTempUnschedulableUntil sets the "temp_unschedulable_until" field.
func (_c *ProviderCreate) SetTempUnschedulableUntil(v time.Time) *ProviderCreate {
	_c.mutation.SetTempUnschedulableUntil(v)
	return _c
}

// SetNillableTempUnschedulableUntil sets the "temp_unschedulable_until" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableTempUnschedulableUntil(v *time.Time) *ProviderCreate {
	if v != nil {
		_c.SetTempUnschedulableUntil(*v)
	}
	return _c
}

// SetTempUnschedulableReason sets the "temp_unschedulable_reason" field.
func (_c *ProviderCreate) SetTempUnschedulableReason(v string) *ProviderCreate {
	_c.mutation.SetTempUnschedulableReason(v)
	return _c
}

// SetNillableTempUnschedulableReason sets the "temp_unschedulable_reason" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableTempUnschedulableReason(v *string) *ProviderCreate {
	if v != nil {
		_c.SetTempUnschedulableReason(*v)
	}
	return _c
}

// SetSessionWindowStart sets the "session_window_start" field.
func (_c *ProviderCreate) SetSessionWindowStart(v time.Time) *ProviderCreate {
	_c.mutation.SetSessionWindowStart(v)
	return _c
}

// SetNillableSessionWindowStart sets the "session_window_start" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableSessionWindowStart(v *time.Time) *ProviderCreate {
	if v != nil {
		_c.SetSessionWindowStart(*v)
	}
	return _c
}

// SetSessionWindowEnd sets the "session_window_end" field.
func (_c *ProviderCreate) SetSessionWindowEnd(v time.Time) *ProviderCreate {
	_c.mutation.SetSessionWindowEnd(v)
	return _c
}

// SetNillableSessionWindowEnd sets the "session_window_end" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableSessionWindowEnd(v *time.Time) *ProviderCreate {
	if v != nil {
		_c.SetSessionWindowEnd(*v)
	}
	return _c
}

// SetSessionWindowStatus sets the "session_window_status" field.
func (_c *ProviderCreate) SetSessionWindowStatus(v string) *ProviderCreate {
	_c.mutation.SetSessionWindowStatus(v)
	return _c
}

// SetNillableSessionWindowStatus sets the "session_window_status" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableSessionWindowStatus(v *string) *ProviderCreate {
	if v != nil {
		_c.SetSessionWindowStatus(*v)
	}
	return _c
}

// SetParentProviderID sets the "parent_provider_id" field.
func (_c *ProviderCreate) SetParentProviderID(v int64) *ProviderCreate {
	_c.mutation.SetParentProviderID(v)
	return _c
}

// SetNillableParentProviderID sets the "parent_provider_id" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableParentProviderID(v *int64) *ProviderCreate {
	if v != nil {
		_c.SetParentProviderID(*v)
	}
	return _c
}

// SetQuotaDimension sets the "quota_dimension" field.
func (_c *ProviderCreate) SetQuotaDimension(v provider.QuotaDimension) *ProviderCreate {
	_c.mutation.SetQuotaDimension(v)
	return _c
}

// SetNillableQuotaDimension sets the "quota_dimension" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableQuotaDimension(v *provider.QuotaDimension) *ProviderCreate {
	if v != nil {
		_c.SetQuotaDimension(*v)
	}
	return _c
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_c *ProviderCreate) AddGroupIDs(ids ...int64) *ProviderCreate {
	_c.mutation.AddGroupIDs(ids...)
	return _c
}

// AddGroups adds the "groups" edges to the Group entity.
func (_c *ProviderCreate) AddGroups(v ...*Group) *ProviderCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupIDs(ids...)
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_c *ProviderCreate) SetProxy(v *Proxy) *ProviderCreate {
	return _c.SetProxyID(v.ID)
}

// SetParentID sets the "parent" edge to the Provider entity by ID.
func (_c *ProviderCreate) SetParentID(id int64) *ProviderCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the Provider entity by ID if the given value is not nil.
func (_c *ProviderCreate) SetNillableParentID(id *int64) *ProviderCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the Provider entity.
func (_c *ProviderCreate) SetParent(v *Provider) *ProviderCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Provider entity by IDs.
func (_c *ProviderCreate) AddChildIDs(ids ...int64) *ProviderCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Provider entity.
func (_c *ProviderCreate) AddChildren(v ...*Provider) *ProviderCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_c *ProviderCreate) AddUsageLogIDs(ids ...int64) *ProviderCreate {
	_c.mutation.AddUsageLogIDs(ids...)
	return _c
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_c *ProviderCreate) AddUsageLogs(v ...*UsageLog) *ProviderCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageLogIDs(ids...)
}

// Mutation returns the ProviderMutation object of the builder.
func (_c *ProviderCreate) Mutation() *ProviderMutation {
	return _c.mutation
}

// Save creates the Provider in the database.
func (_c *ProviderCreate) Save(ctx context.Context) (*Provider, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProviderCreate) SaveX(ctx context.Context) *Provider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProviderCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if provider.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized provider.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := provider.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if provider.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized provider.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := provider.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Credentials(); !ok {
		if provider.DefaultCredentials == nil {
			return fmt.Errorf("ent: uninitialized provider.DefaultCredentials (forgotten import ent/runtime?)")
		}
		v := provider.DefaultCredentials()
		_c.mutation.SetCredentials(v)
	}
	if _, ok := _c.mutation.Extra(); !ok {
		if provider.DefaultExtra == nil {
			return fmt.Errorf("ent: uninitialized provider.DefaultExtra (forgotten import ent/runtime?)")
		}
		v := provider.DefaultExtra()
		_c.mutation.SetExtra(v)
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		v := provider.DefaultConcurrency
		_c.mutation.SetConcurrency(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := provider.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		v := provider.DefaultRateMultiplier
		_c.mutation.SetRateMultiplier(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := provider.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AutoPauseOnExpired(); !ok {
		v := provider.DefaultAutoPauseOnExpired
		_c.mutation.SetAutoPauseOnExpired(v)
	}
	if _, ok := _c.mutation.Schedulable(); !ok {
		v := provider.DefaultSchedulable
		_c.mutation.SetSchedulable(v)
	}
	if _, ok := _c.mutation.QuotaDimension(); !ok {
		v := provider.DefaultQuotaDimension
		_c.mutation.SetQuotaDimension(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProviderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Provider.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Provider.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Provider.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := provider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Provider.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Provider.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := provider.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Provider.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Provider.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := provider.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Provider.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Credentials(); !ok {
		return &ValidationError{Name: "credentials", err: errors.New(`ent: missing required field "Provider.credentials"`)}
	}
	if _, ok := _c.mutation.Extra(); !ok {
		return &ValidationError{Name: "extra", err: errors.New(`ent: missing required field "Provider.extra"`)}
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		return &ValidationError{Name: "concurrency", err: errors.New(`ent: missing required field "Provider.concurrency"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Provider.priority"`)}
	}
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		return &ValidationError{Name: "rate_multiplier", err: errors.New(`ent: missing required field "Provider.rate_multiplier"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Provider.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := provider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Provider.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AutoPauseOnExpired(); !ok {
		return &ValidationError{Name: "auto_pause_on_expired", err: errors.New(`ent: missing required field "Provider.auto_pause_on_expired"`)}
	}
	if _, ok := _c.mutation.Schedulable(); !ok {
		return &ValidationError{Name: "schedulable", err: errors.New(`ent: missing required field "Provider.schedulable"`)}
	}
	if v, ok := _c.mutation.SessionWindowStatus(); ok {
		if err := provider.SessionWindowStatusValidator(v); err != nil {
			return &ValidationError{Name: "session_window_status", err: fmt.Errorf(`ent: validator failed for field "Provider.session_window_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QuotaDimension(); !ok {
		return &ValidationError{Name: "quota_dimension", err: errors.New(`ent: missing required field "Provider.quota_dimension"`)}
	}
	if v, ok := _c.mutation.QuotaDimension(); ok {
		if err := provider.QuotaDimensionValidator(v); err != nil {
			return &ValidationError{Name: "quota_dimension", err: fmt.Errorf(`ent: validator failed for field "Provider.quota_dimension": %w`, err)}
		}
	}
	return nil
}

func (_c *ProviderCreate) sqlSave(ctx context.Context) (*Provider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProviderCreate) createSpec() (*Provider, *sqlgraph.CreateSpec) {
	var (
		_node = &Provider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(provider.Table, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(provider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(provider.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(provider.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(provider.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(provider.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(provider.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(provider.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Credentials(); ok {
		_spec.SetField(provider.FieldCredentials, field.TypeJSON, value)
		_node.Credentials = value
	}
	if value, ok := _c.mutation.Extra(); ok {
		_spec.SetField(provider.FieldExtra, field.TypeJSON, value)
		_node.Extra = value
	}
	if value, ok := _c.mutation.ProxyFallbackOriginID(); ok {
		_spec.SetField(provider.FieldProxyFallbackOriginID, field.TypeInt64, value)
		_node.ProxyFallbackOriginID = &value
	}
	if value, ok := _c.mutation.Concurrency(); ok {
		_spec.SetField(provider.FieldConcurrency, field.TypeInt, value)
		_node.Concurrency = value
	}
	if value, ok := _c.mutation.LoadFactor(); ok {
		_spec.SetField(provider.FieldLoadFactor, field.TypeInt, value)
		_node.LoadFactor = &value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(provider.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.RateMultiplier(); ok {
		_spec.SetField(provider.FieldRateMultiplier, field.TypeFloat64, value)
		_node.RateMultiplier = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(provider.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(provider.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(provider.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(provider.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.AutoPauseOnExpired(); ok {
		_spec.SetField(provider.FieldAutoPauseOnExpired, field.TypeBool, value)
		_node.AutoPauseOnExpired = value
	}
	if value, ok := _c.mutation.Schedulable(); ok {
		_spec.SetField(provider.FieldSchedulable, field.TypeBool, value)
		_node.Schedulable = value
	}
	if value, ok := _c.mutation.RateLimitedAt(); ok {
		_spec.SetField(provider.FieldRateLimitedAt, field.TypeTime, value)
		_node.RateLimitedAt = &value
	}
	if value, ok := _c.mutation.RateLimitResetAt(); ok {
		_spec.SetField(provider.FieldRateLimitResetAt, field.TypeTime, value)
		_node.RateLimitResetAt = &value
	}
	if value, ok := _c.mutation.OverloadUntil(); ok {
		_spec.SetField(provider.FieldOverloadUntil, field.TypeTime, value)
		_node.OverloadUntil = &value
	}
	if value, ok := _c.mutation.TempUnschedulableUntil(); ok {
		_spec.SetField(provider.FieldTempUnschedulableUntil, field.TypeTime, value)
		_node.TempUnschedulableUntil = &value
	}
	if value, ok := _c.mutation.TempUnschedulableReason(); ok {
		_spec.SetField(provider.FieldTempUnschedulableReason, field.TypeString, value)
		_node.TempUnschedulableReason = &value
	}
	if value, ok := _c.mutation.SessionWindowStart(); ok {
		_spec.SetField(provider.FieldSessionWindowStart, field.TypeTime, value)
		_node.SessionWindowStart = &value
	}
	if value, ok := _c.mutation.SessionWindowEnd(); ok {
		_spec.SetField(provider.FieldSessionWindowEnd, field.TypeTime, value)
		_node.SessionWindowEnd = &value
	}
	if value, ok := _c.mutation.SessionWindowStatus(); ok {
		_spec.SetField(provider.FieldSessionWindowStatus, field.TypeString, value)
		_node.SessionWindowStatus = &value
	}
	if value, ok := _c.mutation.QuotaDimension(); ok {
		_spec.SetField(provider.FieldQuotaDimension, field.TypeEnum, value)
		_node.QuotaDimension = value
	}
	if nodes := _c.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   provider.GroupsTable,
			Columns: provider.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProviderGroupCreate{config: _c.config, mutation: newProviderGroupMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   provider.ProxyTable,
			Columns: []string{provider.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProxyID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   provider.ParentTable,
			Columns: []string{provider.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentProviderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.ChildrenTable,
			Columns: []string{provider.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.UsageLogsTable,
			Columns: []string{provider.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Provider.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderCreate) OnConflict(opts ...sql.ConflictOption) *ProviderUpsertOne {
	_c.conflict = opts
	return &ProviderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Provider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderCreate) OnConflictColumns(columns ...string) *ProviderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderUpsertOne{
		create: _c,
	}
}

type (
	// ProviderUpsertOne is the builder for "upsert"-ing
	//  one Provider node.
	ProviderUpsertOne struct {
		create *ProviderCreate
	}

	// ProviderUpsert is the "OnConflict" setter.
	ProviderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderUpsert) SetUpdatedAt(v time.Time) *ProviderUpsert {
	u.Set(provider.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateUpdatedAt() *ProviderUpsert {
	u.SetExcluded(provider.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProviderUpsert) SetDeletedAt(v time.Time) *ProviderUpsert {
	u.Set(provider.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateDeletedAt() *ProviderUpsert {
	u.SetExcluded(provider.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProviderUpsert) ClearDeletedAt() *ProviderUpsert {
	u.SetNull(provider.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *ProviderUpsert) SetName(v string) *ProviderUpsert {
	u.Set(provider.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateName() *ProviderUpsert {
	u.SetExcluded(provider.FieldName)
	return u
}

// SetNotes sets the "notes" field.
func (u *ProviderUpsert) SetNotes(v string) *ProviderUpsert {
	u.Set(provider.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateNotes() *ProviderUpsert {
	u.SetExcluded(provider.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *ProviderUpsert) ClearNotes() *ProviderUpsert {
	u.SetNull(provider.FieldNotes)
	return u
}

// SetPlatform sets the "platform" field.
func (u *ProviderUpsert) SetPlatform(v string) *ProviderUpsert {
	u.Set(provider.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ProviderUpsert) UpdatePlatform() *ProviderUpsert {
	u.SetExcluded(provider.FieldPlatform)
	return u
}

// SetType sets the "type" field.
func (u *ProviderUpsert) SetType(v string) *ProviderUpsert {
	u.Set(provider.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateType() *ProviderUpsert {
	u.SetExcluded(provider.FieldType)
	return u
}

// SetCredentials sets the "credentials" field.
func (u *ProviderUpsert) SetCredentials(v map[string]interface{}) *ProviderUpsert {
	u.Set(provider.FieldCredentials, v)
	return u
}

// UpdateCredentials sets the "credentials" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateCredentials() *ProviderUpsert {
	u.SetExcluded(provider.FieldCredentials)
	return u
}

// SetExtra sets the "extra" field.
func (u *ProviderUpsert) SetExtra(v map[string]interface{}) *ProviderUpsert {
	u.Set(provider.FieldExtra, v)
	return u
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateExtra() *ProviderUpsert {
	u.SetExcluded(provider.FieldExtra)
	return u
}

// SetProxyID sets the "proxy_id" field.
func (u *ProviderUpsert) SetProxyID(v int64) *ProviderUpsert {
	u.Set(provider.FieldProxyID, v)
	return u
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateProxyID() *ProviderUpsert {
	u.SetExcluded(provider.FieldProxyID)
	return u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *ProviderUpsert) ClearProxyID() *ProviderUpsert {
	u.SetNull(provider.FieldProxyID)
	return u
}

// SetProxyFallbackOriginID sets the "proxy_fallback_origin_id" field.
func (u *ProviderUpsert) SetProxyFallbackOriginID(v int64) *ProviderUpsert {
	u.Set(provider.FieldProxyFallbackOriginID, v)
	return u
}

// UpdateProxyFallbackOriginID sets the "proxy_fallback_origin_id" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateProxyFallbackOriginID() *ProviderUpsert {
	u.SetExcluded(provider.FieldProxyFallbackOriginID)
	return u
}

// AddProxyFallbackOriginID adds v to the "proxy_fallback_origin_id" field.
func (u *ProviderUpsert) AddProxyFallbackOriginID(v int64) *ProviderUpsert {
	u.Add(provider.FieldProxyFallbackOriginID, v)
	return u
}

// ClearProxyFallbackOriginID clears the value of the "proxy_fallback_origin_id" field.
func (u *ProviderUpsert) ClearProxyFallbackOriginID() *ProviderUpsert {
	u.SetNull(provider.FieldProxyFallbackOriginID)
	return u
}

// SetConcurrency sets the "concurrency" field.
func (u *ProviderUpsert) SetConcurrency(v int) *ProviderUpsert {
	u.Set(provider.FieldConcurrency, v)
	return u
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateConcurrency() *ProviderUpsert {
	u.SetExcluded(provider.FieldConcurrency)
	return u
}

// AddConcurrency adds v to the "concurrency" field.
func (u *ProviderUpsert) AddConcurrency(v int) *ProviderUpsert {
	u.Add(provider.FieldConcurrency, v)
	return u
}

// SetLoadFactor sets the "load_factor" field.
func (u *ProviderUpsert) SetLoadFactor(v int) *ProviderUpsert {
	u.Set(provider.FieldLoadFactor, v)
	return u
}

// UpdateLoadFactor sets the "load_factor" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateLoadFactor() *ProviderUpsert {
	u.SetExcluded(provider.FieldLoadFactor)
	return u
}

// AddLoadFactor adds v to the "load_factor" field.
func (u *ProviderUpsert) AddLoadFactor(v int) *ProviderUpsert {
	u.Add(provider.FieldLoadFactor, v)
	return u
}

// ClearLoadFactor clears the value of the "load_factor" field.
func (u *ProviderUpsert) ClearLoadFactor() *ProviderUpsert {
	u.SetNull(provider.FieldLoadFactor)
	return u
}

// SetPriority sets the "priority" field.
func (u *ProviderUpsert) SetPriority(v int) *ProviderUpsert {
	u.Set(provider.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ProviderUpsert) UpdatePriority() *ProviderUpsert {
	u.SetExcluded(provider.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *ProviderUpsert) AddPriority(v int) *ProviderUpsert {
	u.Add(provider.FieldPriority, v)
	return u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *ProviderUpsert) SetRateMultiplier(v float64) *ProviderUpsert {
	u.Set(provider.FieldRateMultiplier, v)
	return u
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateRateMultiplier() *ProviderUpsert {
	u.SetExcluded(provider.FieldRateMultiplier)
	return u
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *ProviderUpsert) AddRateMultiplier(v float64) *ProviderUpsert {
	u.Add(provider.FieldRateMultiplier, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ProviderUpsert) SetStatus(v string) *ProviderUpsert {
	u.Set(provider.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateStatus() *ProviderUpsert {
	u.SetExcluded(provider.FieldStatus)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *ProviderUpsert) SetErrorMessage(v string) *ProviderUpsert {
	u.Set(provider.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateErrorMessage() *ProviderUpsert {
	u.SetExcluded(provider.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ProviderUpsert) ClearErrorMessage() *ProviderUpsert {
	u.SetNull(provider.FieldErrorMessage)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *ProviderUpsert) SetLastUsedAt(v time.Time) *ProviderUpsert {
	u.Set(provider.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateLastUsedAt() *ProviderUpsert {
	u.SetExcluded(provider.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *ProviderUpsert) ClearLastUsedAt() *ProviderUpsert {
	u.SetNull(provider.FieldLastUsedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ProviderUpsert) SetExpiresAt(v time.Time) *ProviderUpsert {
	u.Set(provider.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateExpiresAt() *ProviderUpsert {
	u.SetExcluded(provider.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ProviderUpsert) ClearExpiresAt() *ProviderUpsert {
	u.SetNull(provider.FieldExpiresAt)
	return u
}

// SetAutoPauseOnExpired sets the "auto_pause_on_expired" field.
func (u *ProviderUpsert) SetAutoPauseOnExpired(v bool) *ProviderUpsert {
	u.Set(provider.FieldAutoPauseOnExpired, v)
	return u
}

// UpdateAutoPauseOnExpired sets the "auto_pause_on_expired" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateAutoPauseOnExpired() *ProviderUpsert {
	u.SetExcluded(provider.FieldAutoPauseOnExpired)
	return u
}

// SetSchedulable sets the "schedulable" field.
func (u *ProviderUpsert) SetSchedulable(v bool) *ProviderUpsert {
	u.Set(provider.FieldSchedulable, v)
	return u
}

// UpdateSchedulable sets the "schedulable" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateSchedulable() *ProviderUpsert {
	u.SetExcluded(provider.FieldSchedulable)
	return u
}

// SetRateLimitedAt sets the "rate_limited_at" field.
func (u *ProviderUpsert) SetRateLimitedAt(v time.Time) *ProviderUpsert {
	u.Set(provider.FieldRateLimitedAt, v)
	return u
}

// UpdateRateLimitedAt sets the "rate_limited_at" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateRateLimitedAt() *ProviderUpsert {
	u.SetExcluded(provider.FieldRateLimitedAt)
	return u
}

// ClearRateLimitedAt clears the value of the "rate_limited_at" field.
func (u *ProviderUpsert) ClearRateLimitedAt() *ProviderUpsert {
	u.SetNull(provider.FieldRateLimitedAt)
	return u
}

// SetRateLimitResetAt sets the "rate_limit_reset_at" field.
func (u *ProviderUpsert) SetRateLimitResetAt(v time.Time) *ProviderUpsert {
	u.Set(provider.FieldRateLimitResetAt, v)
	return u
}

// UpdateRateLimitResetAt sets the "rate_limit_reset_at" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateRateLimitResetAt() *ProviderUpsert {
	u.SetExcluded(provider.FieldRateLimitResetAt)
	return u
}

// ClearRateLimitResetAt clears the value of the "rate_limit_reset_at" field.
func (u *ProviderUpsert) ClearRateLimitResetAt() *ProviderUpsert {
	u.SetNull(provider.FieldRateLimitResetAt)
	return u
}

// SetOverloadUntil sets the "overload_until" field.
func (u *ProviderUpsert) SetOverloadUntil(v time.Time) *ProviderUpsert {
	u.Set(provider.FieldOverloadUntil, v)
	return u
}

// UpdateOverloadUntil sets the "overload_until" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateOverloadUntil() *ProviderUpsert {
	u.SetExcluded(provider.FieldOverloadUntil)
	return u
}

// ClearOverloadUntil clears the value of the "overload_until" field.
func (u *ProviderUpsert) ClearOverloadUntil() *ProviderUpsert {
	u.SetNull(provider.FieldOverloadUntil)
	return u
}

// SetTempUnschedulableUntil sets the "temp_unschedulable_until" field.
func (u *ProviderUpsert) SetTempUnschedulableUntil(v time.Time) *ProviderUpsert {
	u.Set(provider.FieldTempUnschedulableUntil, v)
	return u
}

// UpdateTempUnschedulableUntil sets the "temp_unschedulable_until" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateTempUnschedulableUntil() *ProviderUpsert {
	u.SetExcluded(provider.FieldTempUnschedulableUntil)
	return u
}

// ClearTempUnschedulableUntil clears the value of the "temp_unschedulable_until" field.
func (u *ProviderUpsert) ClearTempUnschedulableUntil() *ProviderUpsert {
	u.SetNull(provider.FieldTempUnschedulableUntil)
	return u
}

// SetTempUnschedulableReason sets the "temp_unschedulable_reason" field.
func (u *ProviderUpsert) SetTempUnschedulableReason(v string) *ProviderUpsert {
	u.Set(provider.FieldTempUnschedulableReason, v)
	return u
}

// UpdateTempUnschedulableReason sets the "temp_unschedulable_reason" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateTempUnschedulableReason() *ProviderUpsert {
	u.SetExcluded(provider.FieldTempUnschedulableReason)
	return u
}

// ClearTempUnschedulableReason clears the value of the "temp_unschedulable_reason" field.
func (u *ProviderUpsert) ClearTempUnschedulableReason() *ProviderUpsert {
	u.SetNull(provider.FieldTempUnschedulableReason)
	return u
}

// SetSessionWindowStart sets the "session_window_start" field.
func (u *ProviderUpsert) SetSessionWindowStart(v time.Time) *ProviderUpsert {
	u.Set(provider.FieldSessionWindowStart, v)
	return u
}

// UpdateSessionWindowStart sets the "session_window_start" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateSessionWindowStart() *ProviderUpsert {
	u.SetExcluded(provider.FieldSessionWindowStart)
	return u
}

// ClearSessionWindowStart clears the value of the "session_window_start" field.
func (u *ProviderUpsert) ClearSessionWindowStart() *ProviderUpsert {
	u.SetNull(provider.FieldSessionWindowStart)
	return u
}

// SetSessionWindowEnd sets the "session_window_end" field.
func (u *ProviderUpsert) SetSessionWindowEnd(v time.Time) *ProviderUpsert {
	u.Set(provider.FieldSessionWindowEnd, v)
	return u
}

// UpdateSessionWindowEnd sets the "session_window_end" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateSessionWindowEnd() *ProviderUpsert {
	u.SetExcluded(provider.FieldSessionWindowEnd)
	return u
}

// ClearSessionWindowEnd clears the value of the "session_window_end" field.
func (u *ProviderUpsert) ClearSessionWindowEnd() *ProviderUpsert {
	u.SetNull(provider.FieldSessionWindowEnd)
	return u
}

// SetSessionWindowStatus sets the "session_window_status" field.
func (u *ProviderUpsert) SetSessionWindowStatus(v string) *ProviderUpsert {
	u.Set(provider.FieldSessionWindowStatus, v)
	return u
}

// UpdateSessionWindowStatus sets the "session_window_status" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateSessionWindowStatus() *ProviderUpsert {
	u.SetExcluded(provider.FieldSessionWindowStatus)
	return u
}

// ClearSessionWindowStatus clears the value of the "session_window_status" field.
func (u *ProviderUpsert) ClearSessionWindowStatus() *ProviderUpsert {
	u.SetNull(provider.FieldSessionWindowStatus)
	return u
}

// SetParentProviderID sets the "parent_provider_id" field.
func (u *ProviderUpsert) SetParentProviderID(v int64) *ProviderUpsert {
	u.Set(provider.FieldParentProviderID, v)
	return u
}

// UpdateParentProviderID sets the "parent_provider_id" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateParentProviderID() *ProviderUpsert {
	u.SetExcluded(provider.FieldParentProviderID)
	return u
}

// ClearParentProviderID clears the value of the "parent_provider_id" field.
func (u *ProviderUpsert) ClearParentProviderID() *ProviderUpsert {
	u.SetNull(provider.FieldParentProviderID)
	return u
}

// SetQuotaDimension sets the "quota_dimension" field.
func (u *ProviderUpsert) SetQuotaDimension(v provider.QuotaDimension) *ProviderUpsert {
	u.Set(provider.FieldQuotaDimension, v)
	return u
}

// UpdateQuotaDimension sets the "quota_dimension" field to the value that was provided on create.
func (u *ProviderUpsert) UpdateQuotaDimension() *ProviderUpsert {
	u.SetExcluded(provider.FieldQuotaDimension)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Provider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderUpsertOne) UpdateNewValues() *ProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(provider.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Provider.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProviderUpsertOne) Ignore() *ProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderUpsertOne) DoNothing() *ProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderCreate.OnConflict
// documentation for more info.
func (u *ProviderUpsertOne) Update(set func(*ProviderUpsert)) *ProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderUpsertOne) SetUpdatedAt(v time.Time) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateUpdatedAt() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProviderUpsertOne) SetDeletedAt(v time.Time) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateDeletedAt() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProviderUpsertOne) ClearDeletedAt() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ProviderUpsertOne) SetName(v string) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateName() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateName()
	})
}

// SetNotes sets the "notes" field.
func (u *ProviderUpsertOne) SetNotes(v string) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateNotes() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ProviderUpsertOne) ClearNotes() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearNotes()
	})
}

// SetPlatform sets the "platform" field.
func (u *ProviderUpsertOne) SetPlatform(v string) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdatePlatform() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdatePlatform()
	})
}

// SetType sets the "type" field.
func (u *ProviderUpsertOne) SetType(v string) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateType() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateType()
	})
}

// SetCredentials sets the "credentials" field.
func (u *ProviderUpsertOne) SetCredentials(v map[string]interface{}) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetCredentials(v)
	})
}

// UpdateCredentials sets the "credentials" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateCredentials() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateCredentials()
	})
}

// SetExtra sets the "extra" field.
func (u *ProviderUpsertOne) SetExtra(v map[string]interface{}) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetExtra(v)
	})
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateExtra() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateExtra()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *ProviderUpsertOne) SetProxyID(v int64) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateProxyID() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateProxyID()
	})
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *ProviderUpsertOne) ClearProxyID() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearProxyID()
	})
}

// SetProxyFallbackOriginID sets the "proxy_fallback_origin_id" field.
func (u *ProviderUpsertOne) SetProxyFallbackOriginID(v int64) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetProxyFallbackOriginID(v)
	})
}

// AddProxyFallbackOriginID adds v to the "proxy_fallback_origin_id" field.
func (u *ProviderUpsertOne) AddProxyFallbackOriginID(v int64) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.AddProxyFallbackOriginID(v)
	})
}

// UpdateProxyFallbackOriginID sets the "proxy_fallback_origin_id" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateProxyFallbackOriginID() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateProxyFallbackOriginID()
	})
}

// ClearProxyFallbackOriginID clears the value of the "proxy_fallback_origin_id" field.
func (u *ProviderUpsertOne) ClearProxyFallbackOriginID() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearProxyFallbackOriginID()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *ProviderUpsertOne) SetConcurrency(v int) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *ProviderUpsertOne) AddConcurrency(v int) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateConcurrency() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateConcurrency()
	})
}

// SetLoadFactor sets the "load_factor" field.
func (u *ProviderUpsertOne) SetLoadFactor(v int) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetLoadFactor(v)
	})
}

// AddLoadFactor adds v to the "load_factor" field.
func (u *ProviderUpsertOne) AddLoadFactor(v int) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.AddLoadFactor(v)
	})
}

// UpdateLoadFactor sets the "load_factor" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateLoadFactor() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateLoadFactor()
	})
}

// ClearLoadFactor clears the value of the "load_factor" field.
func (u *ProviderUpsertOne) ClearLoadFactor() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearLoadFactor()
	})
}

// SetPriority sets the "priority" field.
func (u *ProviderUpsertOne) SetPriority(v int) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *ProviderUpsertOne) AddPriority(v int) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdatePriority() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdatePriority()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *ProviderUpsertOne) SetRateMultiplier(v float64) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *ProviderUpsertOne) AddRateMultiplier(v float64) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateRateMultiplier() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetStatus sets the "status" field.
func (u *ProviderUpsertOne) SetStatus(v string) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateStatus() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ProviderUpsertOne) SetErrorMessage(v string) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateErrorMessage() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ProviderUpsertOne) ClearErrorMessage() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearErrorMessage()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *ProviderUpsertOne) SetLastUsedAt(v time.Time) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateLastUsedAt() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *ProviderUpsertOne) ClearLastUsedAt() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ProviderUpsertOne) SetExpiresAt(v time.Time) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateExpiresAt() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ProviderUpsertOne) ClearExpiresAt() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearExpiresAt()
	})
}

// SetAutoPauseOnExpired sets the "auto_pause_on_expired" field.
func (u *ProviderUpsertOne) SetAutoPauseOnExpired(v bool) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetAutoPauseOnExpired(v)
	})
}

// UpdateAutoPauseOnExpired sets the "auto_pause_on_expired" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateAutoPauseOnExpired() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateAutoPauseOnExpired()
	})
}

// SetSchedulable sets the "schedulable" field.
func (u *ProviderUpsertOne) SetSchedulable(v bool) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetSchedulable(v)
	})
}

// UpdateSchedulable sets the "schedulable" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateSchedulable() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateSchedulable()
	})
}

// SetRateLimitedAt sets the "rate_limited_at" field.
func (u *ProviderUpsertOne) SetRateLimitedAt(v time.Time) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetRateLimitedAt(v)
	})
}

// UpdateRateLimitedAt sets the "rate_limited_at" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateRateLimitedAt() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateRateLimitedAt()
	})
}

// ClearRateLimitedAt clears the value of the "rate_limited_at" field.
func (u *ProviderUpsertOne) ClearRateLimitedAt() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearRateLimitedAt()
	})
}

// SetRateLimitResetAt sets the "rate_limit_reset_at" field.
func (u *ProviderUpsertOne) SetRateLimitResetAt(v time.Time) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetRateLimitResetAt(v)
	})
}

// UpdateRateLimitResetAt sets the "rate_limit_reset_at" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateRateLimitResetAt() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateRateLimitResetAt()
	})
}

// ClearRateLimitResetAt clears the value of the "rate_limit_reset_at" field.
func (u *ProviderUpsertOne) ClearRateLimitResetAt() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearRateLimitResetAt()
	})
}

// SetOverloadUntil sets the "overload_until" field.
func (u *ProviderUpsertOne) SetOverloadUntil(v time.Time) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetOverloadUntil(v)
	})
}

// UpdateOverloadUntil sets the "overload_until" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateOverloadUntil() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateOverloadUntil()
	})
}

// ClearOverloadUntil clears the value of the "overload_until" field.
func (u *ProviderUpsertOne) ClearOverloadUntil() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearOverloadUntil()
	})
}

// SetTempUnschedulableUntil sets the "temp_unschedulable_until" field.
func (u *ProviderUpsertOne) SetTempUnschedulableUntil(v time.Time) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetTempUnschedulableUntil(v)
	})
}

// UpdateTempUnschedulableUntil sets the "temp_unschedulable_until" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateTempUnschedulableUntil() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateTempUnschedulableUntil()
	})
}

// ClearTempUnschedulableUntil clears the value of the "temp_unschedulable_until" field.
func (u *ProviderUpsertOne) ClearTempUnschedulableUntil() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearTempUnschedulableUntil()
	})
}

// SetTempUnschedulableReason sets the "temp_unschedulable_reason" field.
func (u *ProviderUpsertOne) SetTempUnschedulableReason(v string) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetTempUnschedulableReason(v)
	})
}

// UpdateTempUnschedulableReason sets the "temp_unschedulable_reason" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateTempUnschedulableReason() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateTempUnschedulableReason()
	})
}

// ClearTempUnschedulableReason clears the value of the "temp_unschedulable_reason" field.
func (u *ProviderUpsertOne) ClearTempUnschedulableReason() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearTempUnschedulableReason()
	})
}

// SetSessionWindowStart sets the "session_window_start" field.
func (u *ProviderUpsertOne) SetSessionWindowStart(v time.Time) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetSessionWindowStart(v)
	})
}

// UpdateSessionWindowStart sets the "session_window_start" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateSessionWindowStart() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateSessionWindowStart()
	})
}

// ClearSessionWindowStart clears the value of the "session_window_start" field.
func (u *ProviderUpsertOne) ClearSessionWindowStart() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearSessionWindowStart()
	})
}

// SetSessionWindowEnd sets the "session_window_end" field.
func (u *ProviderUpsertOne) SetSessionWindowEnd(v time.Time) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetSessionWindowEnd(v)
	})
}

// UpdateSessionWindowEnd sets the "session_window_end" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateSessionWindowEnd() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateSessionWindowEnd()
	})
}

// ClearSessionWindowEnd clears the value of the "session_window_end" field.
func (u *ProviderUpsertOne) ClearSessionWindowEnd() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearSessionWindowEnd()
	})
}

// SetSessionWindowStatus sets the "session_window_status" field.
func (u *ProviderUpsertOne) SetSessionWindowStatus(v string) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetSessionWindowStatus(v)
	})
}

// UpdateSessionWindowStatus sets the "session_window_status" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateSessionWindowStatus() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateSessionWindowStatus()
	})
}

// ClearSessionWindowStatus clears the value of the "session_window_status" field.
func (u *ProviderUpsertOne) ClearSessionWindowStatus() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearSessionWindowStatus()
	})
}

// SetParentProviderID sets the "parent_provider_id" field.
func (u *ProviderUpsertOne) SetParentProviderID(v int64) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetParentProviderID(v)
	})
}

// UpdateParentProviderID sets the "parent_provider_id" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateParentProviderID() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateParentProviderID()
	})
}

// ClearParentProviderID clears the value of the "parent_provider_id" field.
func (u *ProviderUpsertOne) ClearParentProviderID() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearParentProviderID()
	})
}

// SetQuotaDimension sets the "quota_dimension" field.
func (u *ProviderUpsertOne) SetQuotaDimension(v provider.QuotaDimension) *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.SetQuotaDimension(v)
	})
}

// UpdateQuotaDimension sets the "quota_dimension" field to the value that was provided on create.
func (u *ProviderUpsertOne) UpdateQuotaDimension() *ProviderUpsertOne {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateQuotaDimension()
	})
}

// Exec executes the query.
func (u *ProviderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProviderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProviderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProviderCreateBulk is the builder for creating many Provider entities in bulk.
type ProviderCreateBulk struct {
	config
	err      error
	builders []*ProviderCreate
	conflict []sql.ConflictOption
}

// Save creates the Provider entities in the database.
func (_c *ProviderCreateBulk) Save(ctx context.Context) ([]*Provider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Provider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProviderCreateBulk) SaveX(ctx context.Context) []*Provider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Provider.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProviderUpsertBulk {
	_c.conflict = opts
	return &ProviderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Provider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderCreateBulk) OnConflictColumns(columns ...string) *ProviderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderUpsertBulk{
		create: _c,
	}
}

// ProviderUpsertBulk is the builder for "upsert"-ing
// a bulk of Provider nodes.
type ProviderUpsertBulk struct {
	create *ProviderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Provider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderUpsertBulk) UpdateNewValues() *ProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(provider.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Provider.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProviderUpsertBulk) Ignore() *ProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderUpsertBulk) DoNothing() *ProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderCreateBulk.OnConflict
// documentation for more info.
func (u *ProviderUpsertBulk) Update(set func(*ProviderUpsert)) *ProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderUpsertBulk) SetUpdatedAt(v time.Time) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateUpdatedAt() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProviderUpsertBulk) SetDeletedAt(v time.Time) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateDeletedAt() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProviderUpsertBulk) ClearDeletedAt() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ProviderUpsertBulk) SetName(v string) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateName() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateName()
	})
}

// SetNotes sets the "notes" field.
func (u *ProviderUpsertBulk) SetNotes(v string) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateNotes() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ProviderUpsertBulk) ClearNotes() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearNotes()
	})
}

// SetPlatform sets the "platform" field.
func (u *ProviderUpsertBulk) SetPlatform(v string) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdatePlatform() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdatePlatform()
	})
}

// SetType sets the "type" field.
func (u *ProviderUpsertBulk) SetType(v string) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateType() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateType()
	})
}

// SetCredentials sets the "credentials" field.
func (u *ProviderUpsertBulk) SetCredentials(v map[string]interface{}) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetCredentials(v)
	})
}

// UpdateCredentials sets the "credentials" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateCredentials() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateCredentials()
	})
}

// SetExtra sets the "extra" field.
func (u *ProviderUpsertBulk) SetExtra(v map[string]interface{}) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetExtra(v)
	})
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateExtra() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateExtra()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *ProviderUpsertBulk) SetProxyID(v int64) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateProxyID() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateProxyID()
	})
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *ProviderUpsertBulk) ClearProxyID() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearProxyID()
	})
}

// SetProxyFallbackOriginID sets the "proxy_fallback_origin_id" field.
func (u *ProviderUpsertBulk) SetProxyFallbackOriginID(v int64) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetProxyFallbackOriginID(v)
	})
}

// AddProxyFallbackOriginID adds v to the "proxy_fallback_origin_id" field.
func (u *ProviderUpsertBulk) AddProxyFallbackOriginID(v int64) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.AddProxyFallbackOriginID(v)
	})
}

// UpdateProxyFallbackOriginID sets the "proxy_fallback_origin_id" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateProxyFallbackOriginID() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateProxyFallbackOriginID()
	})
}

// ClearProxyFallbackOriginID clears the value of the "proxy_fallback_origin_id" field.
func (u *ProviderUpsertBulk) ClearProxyFallbackOriginID() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearProxyFallbackOriginID()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *ProviderUpsertBulk) SetConcurrency(v int) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *ProviderUpsertBulk) AddConcurrency(v int) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateConcurrency() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateConcurrency()
	})
}

// SetLoadFactor sets the "load_factor" field.
func (u *ProviderUpsertBulk) SetLoadFactor(v int) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetLoadFactor(v)
	})
}

// AddLoadFactor adds v to the "load_factor" field.
func (u *ProviderUpsertBulk) AddLoadFactor(v int) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.AddLoadFactor(v)
	})
}

// UpdateLoadFactor sets the "load_factor" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateLoadFactor() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateLoadFactor()
	})
}

// ClearLoadFactor clears the value of the "load_factor" field.
func (u *ProviderUpsertBulk) ClearLoadFactor() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearLoadFactor()
	})
}

// SetPriority sets the "priority" field.
func (u *ProviderUpsertBulk) SetPriority(v int) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *ProviderUpsertBulk) AddPriority(v int) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdatePriority() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdatePriority()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *ProviderUpsertBulk) SetRateMultiplier(v float64) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *ProviderUpsertBulk) AddRateMultiplier(v float64) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateRateMultiplier() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetStatus sets the "status" field.
func (u *ProviderUpsertBulk) SetStatus(v string) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateStatus() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ProviderUpsertBulk) SetErrorMessage(v string) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateErrorMessage() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ProviderUpsertBulk) ClearErrorMessage() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearErrorMessage()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *ProviderUpsertBulk) SetLastUsedAt(v time.Time) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateLastUsedAt() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *ProviderUpsertBulk) ClearLastUsedAt() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ProviderUpsertBulk) SetExpiresAt(v time.Time) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateExpiresAt() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ProviderUpsertBulk) ClearExpiresAt() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearExpiresAt()
	})
}

// SetAutoPauseOnExpired sets the "auto_pause_on_expired" field.
func (u *ProviderUpsertBulk) SetAutoPauseOnExpired(v bool) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetAutoPauseOnExpired(v)
	})
}

// UpdateAutoPauseOnExpired sets the "auto_pause_on_expired" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateAutoPauseOnExpired() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateAutoPauseOnExpired()
	})
}

// SetSchedulable sets the "schedulable" field.
func (u *ProviderUpsertBulk) SetSchedulable(v bool) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetSchedulable(v)
	})
}

// UpdateSchedulable sets the "schedulable" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateSchedulable() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateSchedulable()
	})
}

// SetRateLimitedAt sets the "rate_limited_at" field.
func (u *ProviderUpsertBulk) SetRateLimitedAt(v time.Time) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetRateLimitedAt(v)
	})
}

// UpdateRateLimitedAt sets the "rate_limited_at" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateRateLimitedAt() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateRateLimitedAt()
	})
}

// ClearRateLimitedAt clears the value of the "rate_limited_at" field.
func (u *ProviderUpsertBulk) ClearRateLimitedAt() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearRateLimitedAt()
	})
}

// SetRateLimitResetAt sets the "rate_limit_reset_at" field.
func (u *ProviderUpsertBulk) SetRateLimitResetAt(v time.Time) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetRateLimitResetAt(v)
	})
}

// UpdateRateLimitResetAt sets the "rate_limit_reset_at" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateRateLimitResetAt() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateRateLimitResetAt()
	})
}

// ClearRateLimitResetAt clears the value of the "rate_limit_reset_at" field.
func (u *ProviderUpsertBulk) ClearRateLimitResetAt() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearRateLimitResetAt()
	})
}

// SetOverloadUntil sets the "overload_until" field.
func (u *ProviderUpsertBulk) SetOverloadUntil(v time.Time) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetOverloadUntil(v)
	})
}

// UpdateOverloadUntil sets the "overload_until" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateOverloadUntil() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateOverloadUntil()
	})
}

// ClearOverloadUntil clears the value of the "overload_until" field.
func (u *ProviderUpsertBulk) ClearOverloadUntil() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearOverloadUntil()
	})
}

// SetTempUnschedulableUntil sets the "temp_unschedulable_until" field.
func (u *ProviderUpsertBulk) SetTempUnschedulableUntil(v time.Time) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetTempUnschedulableUntil(v)
	})
}

// UpdateTempUnschedulableUntil sets the "temp_unschedulable_until" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateTempUnschedulableUntil() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateTempUnschedulableUntil()
	})
}

// ClearTempUnschedulableUntil clears the value of the "temp_unschedulable_until" field.
func (u *ProviderUpsertBulk) ClearTempUnschedulableUntil() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearTempUnschedulableUntil()
	})
}

// SetTempUnschedulableReason sets the "temp_unschedulable_reason" field.
func (u *ProviderUpsertBulk) SetTempUnschedulableReason(v string) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetTempUnschedulableReason(v)
	})
}

// UpdateTempUnschedulableReason sets the "temp_unschedulable_reason" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateTempUnschedulableReason() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateTempUnschedulableReason()
	})
}

// ClearTempUnschedulableReason clears the value of the "temp_unschedulable_reason" field.
func (u *ProviderUpsertBulk) ClearTempUnschedulableReason() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearTempUnschedulableReason()
	})
}

// SetSessionWindowStart sets the "session_window_start" field.
func (u *ProviderUpsertBulk) SetSessionWindowStart(v time.Time) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetSessionWindowStart(v)
	})
}

// UpdateSessionWindowStart sets the "session_window_start" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateSessionWindowStart() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateSessionWindowStart()
	})
}

// ClearSessionWindowStart clears the value of the "session_window_start" field.
func (u *ProviderUpsertBulk) ClearSessionWindowStart() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearSessionWindowStart()
	})
}

// SetSessionWindowEnd sets the "session_window_end" field.
func (u *ProviderUpsertBulk) SetSessionWindowEnd(v time.Time) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetSessionWindowEnd(v)
	})
}

// UpdateSessionWindowEnd sets the "session_window_end" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateSessionWindowEnd() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateSessionWindowEnd()
	})
}

// ClearSessionWindowEnd clears the value of the "session_window_end" field.
func (u *ProviderUpsertBulk) ClearSessionWindowEnd() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearSessionWindowEnd()
	})
}

// SetSessionWindowStatus sets the "session_window_status" field.
func (u *ProviderUpsertBulk) SetSessionWindowStatus(v string) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetSessionWindowStatus(v)
	})
}

// UpdateSessionWindowStatus sets the "session_window_status" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateSessionWindowStatus() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateSessionWindowStatus()
	})
}

// ClearSessionWindowStatus clears the value of the "session_window_status" field.
func (u *ProviderUpsertBulk) ClearSessionWindowStatus() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearSessionWindowStatus()
	})
}

// SetParentProviderID sets the "parent_provider_id" field.
func (u *ProviderUpsertBulk) SetParentProviderID(v int64) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetParentProviderID(v)
	})
}

// UpdateParentProviderID sets the "parent_provider_id" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateParentProviderID() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateParentProviderID()
	})
}

// ClearParentProviderID clears the value of the "parent_provider_id" field.
func (u *ProviderUpsertBulk) ClearParentProviderID() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.ClearParentProviderID()
	})
}

// SetQuotaDimension sets the "quota_dimension" field.
func (u *ProviderUpsertBulk) SetQuotaDimension(v provider.QuotaDimension) *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.SetQuotaDimension(v)
	})
}

// UpdateQuotaDimension sets the "quota_dimension" field to the value that was provided on create.
func (u *ProviderUpsertBulk) UpdateQuotaDimension() *ProviderUpsertBulk {
	return u.Update(func(s *ProviderUpsert) {
		s.UpdateQuotaDimension()
	})
}

// Exec executes the query.
func (u *ProviderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProviderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
