// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TokenFlux/TokenRouter/ent/group"
	"github.com/TokenFlux/TokenRouter/ent/provider"
	"github.com/TokenFlux/TokenRouter/ent/providergroup"
)

// ProviderGroupCreate is the builder for creating a ProviderGroup entity.
type ProviderGroupCreate struct {
	config
	mutation *ProviderGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProviderID sets the "provider_id" field.
func (_c *ProviderGroupCreate) SetProviderID(v int64) *ProviderGroupCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ProviderGroupCreate) SetGroupID(v int64) *ProviderGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProviderGroupCreate) SetCreatedAt(v time.Time) *ProviderGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProviderGroupCreate) SetNillableCreatedAt(v *time.Time) *ProviderGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetProvider sets the "provider" edge to the Provider entity.
func (_c *ProviderGroupCreate) SetProvider(v *Provider) *ProviderGroupCreate {
	return _c.SetProviderID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *ProviderGroupCreate) SetGroup(v *Group) *ProviderGroupCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the ProviderGroupMutation object of the builder.
func (_c *ProviderGroupCreate) Mutation() *ProviderGroupMutation {
	return _c.mutation
}

// Save creates the ProviderGroup in the database.
func (_c *ProviderGroupCreate) Save(ctx context.Context) (*ProviderGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProviderGroupCreate) SaveX(ctx context.Context) *ProviderGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProviderGroupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := providergroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProviderGroupCreate) check() error {
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "ProviderGroup.provider_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "ProviderGroup.group_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProviderGroup.created_at"`)}
	}
	if len(_c.mutation.ProviderIDs()) == 0 {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required edge "ProviderGroup.provider"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "ProviderGroup.group"`)}
	}
	return nil
}

func (_c *ProviderGroupCreate) sqlSave(ctx context.Context) (*ProviderGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *ProviderGroupCreate) createSpec() (*ProviderGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(providergroup.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(providergroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   providergroup.ProviderTable,
			Columns: []string{providergroup.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProviderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   providergroup.GroupTable,
			Columns: []string{providergroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderGroup.Create().
//		SetProviderID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderGroupUpsert) {
//			SetProviderID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderGroupCreate) OnConflict(opts ...sql.ConflictOption) *ProviderGroupUpsertOne {
	_c.conflict = opts
	return &ProviderGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderGroupCreate) OnConflictColumns(columns ...string) *ProviderGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderGroupUpsertOne{
		create: _c,
	}
}

type (
	// ProviderGroupUpsertOne is the builder for "upsert"-ing
	//  one ProviderGroup node.
	ProviderGroupUpsertOne struct {
		create *ProviderGroupCreate
	}

	// ProviderGroupUpsert is the "OnConflict" setter.
	ProviderGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetProviderID sets the "provider_id" field.
func (u *ProviderGroupUpsert) SetProviderID(v int64) *ProviderGroupUpsert {
	u.Set(providergroup.FieldProviderID, v)
	return u
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *ProviderGroupUpsert) UpdateProviderID() *ProviderGroupUpsert {
	u.SetExcluded(providergroup.FieldProviderID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *ProviderGroupUpsert) SetGroupID(v int64) *ProviderGroupUpsert {
	u.Set(providergroup.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ProviderGroupUpsert) UpdateGroupID() *ProviderGroupUpsert {
	u.SetExcluded(providergroup.FieldGroupID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProviderGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderGroupUpsertOne) UpdateNewValues() *ProviderGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(providergroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProviderGroupUpsertOne) Ignore() *ProviderGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderGroupUpsertOne) DoNothing() *ProviderGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderGroupCreate.OnConflict
// documentation for more info.
func (u *ProviderGroupUpsertOne) Update(set func(*ProviderGroupUpsert)) *ProviderGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderID sets the "provider_id" field.
func (u *ProviderGroupUpsertOne) SetProviderID(v int64) *ProviderGroupUpsertOne {
	return u.Update(func(s *ProviderGroupUpsert) {
		s.SetProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *ProviderGroupUpsertOne) UpdateProviderID() *ProviderGroupUpsertOne {
	return u.Update(func(s *ProviderGroupUpsert) {
		s.UpdateProviderID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ProviderGroupUpsertOne) SetGroupID(v int64) *ProviderGroupUpsertOne {
	return u.Update(func(s *ProviderGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ProviderGroupUpsertOne) UpdateGroupID() *ProviderGroupUpsertOne {
	return u.Update(func(s *ProviderGroupUpsert) {
		s.UpdateGroupID()
	})
}

// Exec executes the query.
func (u *ProviderGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// ProviderGroupCreateBulk is the builder for creating many ProviderGroup entities in bulk.
type ProviderGroupCreateBulk struct {
	config
	err      error
	builders []*ProviderGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the ProviderGroup entities in the database.
func (_c *ProviderGroupCreateBulk) Save(ctx context.Context) ([]*ProviderGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProviderGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProviderGroupCreateBulk) SaveX(ctx context.Context) []*ProviderGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderGroupUpsert) {
//			SetProviderID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProviderGroupUpsertBulk {
	_c.conflict = opts
	return &ProviderGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderGroupCreateBulk) OnConflictColumns(columns ...string) *ProviderGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderGroupUpsertBulk{
		create: _c,
	}
}

// ProviderGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of ProviderGroup nodes.
type ProviderGroupUpsertBulk struct {
	create *ProviderGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProviderGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderGroupUpsertBulk) UpdateNewValues() *ProviderGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(providergroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProviderGroupUpsertBulk) Ignore() *ProviderGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderGroupUpsertBulk) DoNothing() *ProviderGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderGroupCreateBulk.OnConflict
// documentation for more info.
func (u *ProviderGroupUpsertBulk) Update(set func(*ProviderGroupUpsert)) *ProviderGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderID sets the "provider_id" field.
func (u *ProviderGroupUpsertBulk) SetProviderID(v int64) *ProviderGroupUpsertBulk {
	return u.Update(func(s *ProviderGroupUpsert) {
		s.SetProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *ProviderGroupUpsertBulk) UpdateProviderID() *ProviderGroupUpsertBulk {
	return u.Update(func(s *ProviderGroupUpsert) {
		s.UpdateProviderID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ProviderGroupUpsertBulk) SetGroupID(v int64) *ProviderGroupUpsertBulk {
	return u.Update(func(s *ProviderGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ProviderGroupUpsertBulk) UpdateGroupID() *ProviderGroupUpsertBulk {
	return u.Update(func(s *ProviderGroupUpsert) {
		s.UpdateGroupID()
	})
}

// Exec executes the query.
func (u *ProviderGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProviderGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
