// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TokenFlux/TokenRouter/ent/group"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
	"github.com/TokenFlux/TokenRouter/ent/provider"
	"github.com/TokenFlux/TokenRouter/ent/proxy"
	"github.com/TokenFlux/TokenRouter/ent/usagelog"
)

// ProviderUpdate is the builder for updating Provider entities.
type ProviderUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderMutation
}

// Where appends a list predicates to the ProviderUpdate builder.
func (_u *ProviderUpdate) Where(ps ...predicate.Provider) *ProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderUpdate) SetUpdatedAt(v time.Time) *ProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProviderUpdate) SetDeletedAt(v time.Time) *ProviderUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableDeletedAt(v *time.Time) *ProviderUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProviderUpdate) ClearDeletedAt() *ProviderUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *ProviderUpdate) SetName(v string) *ProviderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableName(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ProviderUpdate) SetNotes(v string) *ProviderUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableNotes(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ProviderUpdate) ClearNotes() *ProviderUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ProviderUpdate) SetPlatform(v string) *ProviderUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillablePlatform(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ProviderUpdate) SetType(v string) *ProviderUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableType(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetCredentials sets the "credentials" field.
func (_u *ProviderUpdate) SetCredentials(v map[string]interface{}) *ProviderUpdate {
	_u.mutation.SetCredentials(v)
	return _u
}

// SetExtra sets the "extra" field.
func (_u *ProviderUpdate) SetExtra(v map[string]interface{}) *ProviderUpdate {
	_u.mutation.SetExtra(v)
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *ProviderUpdate) SetProxyID(v int64) *ProviderUpdate {
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableProxyID(v *int64) *ProviderUpdate {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (_u *ProviderUpdate) ClearProxyID() *ProviderUpdate {
	_u.mutation.ClearProxyID()
	return _u
}

// SetProxyFallbackOriginID sets the "proxy_fallback_origin_id" field.
func (_u *ProviderUpdate) SetProxyFallbackOriginID(v int64) *ProviderUpdate {
	_u.mutation.ResetProxyFallbackOriginID()
	_u.mutation.SetProxyFallbackOriginID(v)
	return _u
}

// SetNillableProxyFallbackOriginID sets the "proxy_fallback_origin_id" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableProxyFallbackOriginID(v *int64) *ProviderUpdate {
	if v != nil {
		_u.SetProxyFallbackOriginID(*v)
	}
	return _u
}

// AddProxyFallbackOriginID adds value to the "proxy_fallback_origin_id" field.
func (_u *ProviderUpdate) AddProxyFallbackOriginID(v int64) *ProviderUpdate {
	_u.mutation.AddProxyFallbackOriginID(v)
	return _u
}

// ClearProxyFallbackOriginID clears the value of the "proxy_fallback_origin_id" field.
func (_u *ProviderUpdate) ClearProxyFallbackOriginID() *ProviderUpdate {
	_u.mutation.ClearProxyFallbackOriginID()
	return _u
}

// SetConcurrency sets the "concurrency" field.
func (_u *ProviderUpdate) SetConcurrency(v int) *ProviderUpdate {
	_u.mutation.ResetConcurrency()
	_u.mutation.SetConcurrency(v)
	return _u
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableConcurrency(v *int) *ProviderUpdate {
	if v != nil {
		_u.SetConcurrency(*v)
	}
	return _u
}

// AddConcurrency adds value to the "concurrency" field.
func (_u *ProviderUpdate) AddConcurrency(v int) *ProviderUpdate {
	_u.mutation.AddConcurrency(v)
	return _u
}

// SetLoadFactor sets the "load_factor" field.
func (_u *ProviderUpdate) SetLoadFactor(v int) *ProviderUpdate {
	_u.mutation.ResetLoadFactor()
	_u.mutation.SetLoadFactor(v)
	return _u
}

// SetNillableLoadFactor sets the "load_factor" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableLoadFactor(v *int) *ProviderUpdate {
	if v != nil {
		_u.SetLoadFactor(*v)
	}
	return _u
}

// AddLoadFactor adds value to the "load_factor" field.
func (_u *ProviderUpdate) AddLoadFactor(v int) *ProviderUpdate {
	_u.mutation.AddLoadFactor(v)
	return _u
}

// ClearLoadFactor clears the value of the "load_factor" field.
func (_u *ProviderUpdate) ClearLoadFactor() *ProviderUpdate {
	_u.mutation.ClearLoadFactor()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ProviderUpdate) SetPriority(v int) *ProviderUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillablePriority(v *int) *ProviderUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ProviderUpdate) AddPriority(v int) *ProviderUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *ProviderUpdate) SetRateMultiplier(v float64) *ProviderUpdate {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableRateMultiplier(v *float64) *ProviderUpdate {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *ProviderUpdate) AddRateMultiplier(v float64) *ProviderUpdate {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderUpdate) SetStatus(v string) *ProviderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableStatus(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ProviderUpdate) SetErrorMessage(v string) *ProviderUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableErrorMessage(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ProviderUpdate) ClearErrorMessage() *ProviderUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *ProviderUpdate) SetLastUsedAt(v time.Time) *ProviderUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableLastUsedAt(v *time.Time) *ProviderUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *ProviderUpdate) ClearLastUsedAt() *ProviderUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ProviderUpdate) SetExpiresAt(v time.Time) *ProviderUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableExpiresAt(v *time.Time) *ProviderUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ProviderUpdate) ClearExpiresAt() *ProviderUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetAutoPauseOnExpired sets the "auto_pause_on_expired" field.
func (_u *ProviderUpdate) SetAutoPauseOnExpired(v bool) *ProviderUpdate {
	_u.mutation.SetAutoPauseOnExpired(v)
	return _u
}

// SetNillableAutoPauseOnExpired sets the "auto_pause_on_expired" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableAutoPauseOnExpired(v *bool) *ProviderUpdate {
	if v != nil {
		_u.SetAutoPauseOnExpired(*v)
	}
	return _u
}

// SetSchedulable sets the "schedulable" field.
func (_u *ProviderUpdate) SetSchedulable(v bool) *ProviderUpdate {
	_u.mutation.SetSchedulable(v)
	return _u
}

// SetNillableSchedulable sets the "schedulable" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableSchedulable(v *bool) *ProviderUpdate {
	if v != nil {
		_u.SetSchedulable(*v)
	}
	return _u
}

// SetRateLimitedAt sets the "rate_limited_at" field.
func (_u *ProviderUpdate) SetRateLimitedAt(v time.Time) *ProviderUpdate {
	_u.mutation.SetRateLimitedAt(v)
	return _u
}

// SetNillableRateLimitedAt sets the "rate_limited_at" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableRateLimitedAt(v *time.Time) *ProviderUpdate {
	if v != nil {
		_u.SetRateLimitedAt(*v)
	}
	return _u
}

// ClearRateLimitedAt clears the value of the "rate_limited_at" field.
func (_u *ProviderUpdate) ClearRateLimitedAt() *ProviderUpdate {
	_u.mutation.ClearRateLimitedAt()
	return _u
}

// SetRateLimitResetAt sets the "rate_limit_reset_at" field.
func (_u *ProviderUpdate) SetRateLimitResetAt(v time.Time) *ProviderUpdate {
	_u.mutation.SetRateLimitResetAt(v)
	return _u
}

// SetNillableRateLimitResetAt sets the "rate_limit_reset_at" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableRateLimitResetAt(v *time.Time) *ProviderUpdate {
	if v != nil {
		_u.SetRateLimitResetAt(*v)
	}
	return _u
}

// ClearRateLimitResetAt clears the value of the "rate_limit_reset_at" field.
func (_u *ProviderUpdate) ClearRateLimitResetAt() *ProviderUpdate {
	_u.mutation.ClearRateLimitResetAt()
	return _u
}

// SetOverloadUntil sets the "overload_until" field.
func (_u *ProviderUpdate) SetOverloadUntil(v time.Time) *ProviderUpdate {
	_u.mutation.SetOverloadUntil(v)
	return _u
}

// SetNillableOverloadUntil sets the "overload_until" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableOverloadUntil(v *time.Time) *ProviderUpdate {
	if v != nil {
		_u.SetOverloadUntil(*v)
	}
	return _u
}

// ClearOverloadUntil clears the value of the "overload_until" field.
func (_u *ProviderUpdate) ClearOverloadUntil() *ProviderUpdate {
	_u.mutation.ClearOverloadUntil()
	return _u
}

// SetTempUnschedulableUntil sets the "temp_unschedulable_until" field.
func (_u *ProviderUpdate) SetTempUnschedulableUntil(v time.Time) *ProviderUpdate {
	_u.mutation.SetTempUnschedulableUntil(v)
	return _u
}

// SetNillableTempUnschedulableUntil sets the "temp_unschedulable_until" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableTempUnschedulableUntil(v *time.Time) *ProviderUpdate {
	if v != nil {
		_u.SetTempUnschedulableUntil(*v)
	}
	return _u
}

// ClearTempUnschedulableUntil clears the value of the "temp_unschedulable_until" field.
func (_u *ProviderUpdate) ClearTempUnschedulableUntil() *ProviderUpdate {
	_u.mutation.ClearTempUnschedulableUntil()
	return _u
}

// SetTempUnschedulableReason sets the "temp_unschedulable_reason" field.
func (_u *ProviderUpdate) SetTempUnschedulableReason(v string) *ProviderUpdate {
	_u.mutation.SetTempUnschedulableReason(v)
	return _u
}

// SetNillableTempUnschedulableReason sets the "temp_unschedulable_reason" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableTempUnschedulableReason(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetTempUnschedulableReason(*v)
	}
	return _u
}

// ClearTempUnschedulableReason clears the value of the "temp_unschedulable_reason" field.
func (_u *ProviderUpdate) ClearTempUnschedulableReason() *ProviderUpdate {
	_u.mutation.ClearTempUnschedulableReason()
	return _u
}

// SetSessionWindowStart sets the "session_window_start" field.
func (_u *ProviderUpdate) SetSessionWindowStart(v time.Time) *ProviderUpdate {
	_u.mutation.SetSessionWindowStart(v)
	return _u
}

// SetNillableSessionWindowStart sets the "session_window_start" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableSessionWindowStart(v *time.Time) *ProviderUpdate {
	if v != nil {
		_u.SetSessionWindowStart(*v)
	}
	return _u
}

// ClearSessionWindowStart clears the value of the "session_window_start" field.
func (_u *ProviderUpdate) ClearSessionWindowStart() *ProviderUpdate {
	_u.mutation.ClearSessionWindowStart()
	return _u
}

// SetSessionWindowEnd sets the "session_window_end" field.
func (_u *ProviderUpdate) SetSessionWindowEnd(v time.Time) *ProviderUpdate {
	_u.mutation.SetSessionWindowEnd(v)
	return _u
}

// SetNillableSessionWindowEnd sets the "session_window_end" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableSessionWindowEnd(v *time.Time) *ProviderUpdate {
	if v != nil {
		_u.SetSessionWindowEnd(*v)
	}
	return _u
}

// ClearSessionWindowEnd clears the value of the "session_window_end" field.
func (_u *ProviderUpdate) ClearSessionWindowEnd() *ProviderUpdate {
	_u.mutation.ClearSessionWindowEnd()
	return _u
}

// SetSessionWindowStatus sets the "session_window_status" field.
func (_u *ProviderUpdate) SetSessionWindowStatus(v string) *ProviderUpdate {
	_u.mutation.SetSessionWindowStatus(v)
	return _u
}

// SetNillableSessionWindowStatus sets the "session_window_status" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableSessionWindowStatus(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetSessionWindowStatus(*v)
	}
	return _u
}

// ClearSessionWindowStatus clears the value of the "session_window_status" field.
func (_u *ProviderUpdate) ClearSessionWindowStatus() *ProviderUpdate {
	_u.mutation.ClearSessionWindowStatus()
	return _u
}

// SetParentProviderID sets the "parent_provider_id" field.
func (_u *ProviderUpdate) SetParentProviderID(v int64) *ProviderUpdate {
	_u.mutation.SetParentProviderID(v)
	return _u
}

// SetNillableParentProviderID sets the "parent_provider_id" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableParentProviderID(v *int64) *ProviderUpdate {
	if v != nil {
		_u.SetParentProviderID(*v)
	}
	return _u
}

// ClearParentProviderID clears the value of the "parent_provider_id" field.
func (_u *ProviderUpdate) ClearParentProviderID() *ProviderUpdate {
	_u.mutation.ClearParentProviderID()
	return _u
}

// SetQuotaDimension sets the "quota_dimension" field.
func (_u *ProviderUpdate) SetQuotaDimension(v provider.QuotaDimension) *ProviderUpdate {
	_u.mutation.SetQuotaDimension(v)
	return _u
}

// SetNillableQuotaDimension sets the "quota_dimension" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableQuotaDimension(v *provider.QuotaDimension) *ProviderUpdate {
	if v != nil {
		_u.SetQuotaDimension(*v)
	}
	return _u
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *ProviderUpdate) AddGroupIDs(ids ...int64) *ProviderUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *ProviderUpdate) AddGroups(v ...*Group) *ProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_u *ProviderUpdate) SetProxy(v *Proxy) *ProviderUpdate {
	return _u.SetProxyID(v.ID)
}

// SetParentID sets the "parent" edge to the Provider entity by ID.
func (_u *ProviderUpdate) SetParentID(id int64) *ProviderUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Provider entity by ID if the given value is not nil.
func (_u *ProviderUpdate) SetNillableParentID(id *int64) *ProviderUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Provider entity.
func (_u *ProviderUpdate) SetParent(v *Provider) *ProviderUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Provider entity by IDs.
func (_u *ProviderUpdate) AddChildIDs(ids ...int64) *ProviderUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Provider entity.
func (_u *ProviderUpdate) AddChildren(v ...*Provider) *ProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *ProviderUpdate) AddUsageLogIDs(ids ...int64) *ProviderUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *ProviderUpdate) AddUsageLogs(v ...*UsageLog) *ProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the ProviderMutation object of the builder.
func (_u *ProviderUpdate) Mutation() *ProviderMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *ProviderUpdate) ClearGroups() *ProviderUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *ProviderUpdate) RemoveGroupIDs(ids ...int64) *ProviderUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *ProviderUpdate) RemoveGroups(v ...*Group) *ProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (_u *ProviderUpdate) ClearProxy() *ProviderUpdate {
	_u.mutation.ClearProxy()
	return _u
}

// ClearParent clears the "parent" edge to the Provider entity.
func (_u *ProviderUpdate) ClearParent() *ProviderUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Provider entity.
func (_u *ProviderUpdate) ClearChildren() *ProviderUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Provider entities by IDs.
func (_u *ProviderUpdate) RemoveChildIDs(ids ...int64) *ProviderUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Provider entities.
func (_u *ProviderUpdate) RemoveChildren(v ...*Provider) *ProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *ProviderUpdate) ClearUsageLogs() *ProviderUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *ProviderUpdate) RemoveUsageLogIDs(ids ...int64) *ProviderUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *ProviderUpdate) RemoveUsageLogs(v ...*UsageLog) *ProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if provider.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized provider.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := provider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := provider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Provider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := provider.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Provider.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := provider.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Provider.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := provider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Provider.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionWindowStatus(); ok {
		if err := provider.SessionWindowStatusValidator(v); err != nil {
			return &ValidationError{Name: "session_window_status", err: fmt.Errorf(`ent: validator failed for field "Provider.session_window_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaDimension(); ok {
		if err := provider.QuotaDimensionValidator(v); err != nil {
			return &ValidationError{Name: "quota_dimension", err: fmt.Errorf(`ent: validator failed for field "Provider.quota_dimension": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(provider.Table, provider.Columns, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(provider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(provider.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(provider.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(provider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(provider.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(provider.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(provider.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(provider.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Credentials(); ok {
		_spec.SetField(provider.FieldCredentials, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Extra(); ok {
		_spec.SetField(provider.FieldExtra, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ProxyFallbackOriginID(); ok {
		_spec.SetField(provider.FieldProxyFallbackOriginID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProxyFallbackOriginID(); ok {
		_spec.AddField(provider.FieldProxyFallbackOriginID, field.TypeInt64, value)
	}
	if _u.mutation.ProxyFallbackOriginIDCleared() {
		_spec.ClearField(provider.FieldProxyFallbackOriginID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Concurrency(); ok {
		_spec.SetField(provider.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrency(); ok {
		_spec.AddField(provider.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LoadFactor(); ok {
		_spec.SetField(provider.FieldLoadFactor, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLoadFactor(); ok {
		_spec.AddField(provider.FieldLoadFactor, field.TypeInt, value)
	}
	if _u.mutation.LoadFactorCleared() {
		_spec.ClearField(provider.FieldLoadFactor, field.TypeInt)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(provider.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(provider.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(provider.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(provider.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(provider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(provider.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(provider.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(provider.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(provider.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(provider.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(provider.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AutoPauseOnExpired(); ok {
		_spec.SetField(provider.FieldAutoPauseOnExpired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Schedulable(); ok {
		_spec.SetField(provider.FieldSchedulable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RateLimitedAt(); ok {
		_spec.SetField(provider.FieldRateLimitedAt, field.TypeTime, value)
	}
	if _u.mutation.RateLimitedAtCleared() {
		_spec.ClearField(provider.FieldRateLimitedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RateLimitResetAt(); ok {
		_spec.SetField(provider.FieldRateLimitResetAt, field.TypeTime, value)
	}
	if _u.mutation.RateLimitResetAtCleared() {
		_spec.ClearField(provider.FieldRateLimitResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OverloadUntil(); ok {
		_spec.SetField(provider.FieldOverloadUntil, field.TypeTime, value)
	}
	if _u.mutation.OverloadUntilCleared() {
		_spec.ClearField(provider.FieldOverloadUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.TempUnschedulableUntil(); ok {
		_spec.SetField(provider.FieldTempUnschedulableUntil, field.TypeTime, value)
	}
	if _u.mutation.TempUnschedulableUntilCleared() {
		_spec.ClearField(provider.FieldTempUnschedulableUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.TempUnschedulableReason(); ok {
		_spec.SetField(provider.FieldTempUnschedulableReason, field.TypeString, value)
	}
	if _u.mutation.TempUnschedulableReasonCleared() {
		_spec.ClearField(provider.FieldTempUnschedulableReason, field.TypeString)
	}
	if value, ok := _u.mutation.SessionWindowStart(); ok {
		_spec.SetField(provider.FieldSessionWindowStart, field.TypeTime, value)
	}
	if _u.mutation.SessionWindowStartCleared() {
		_spec.ClearField(provider.FieldSessionWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.SessionWindowEnd(); ok {
		_spec.SetField(provider.FieldSessionWindowEnd, field.TypeTime, value)
	}
	if _u.mutation.SessionWindowEndCleared() {
		_spec.ClearField(provider.FieldSessionWindowEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.SessionWindowStatus(); ok {
		_spec.SetField(provider.FieldSessionWindowStatus, field.TypeString, value)
	}
	if _u.mutation.SessionWindowStatusCleared() {
		_spec.ClearField(provider.FieldSessionWindowStatus, field.TypeString)
	}
	if value, ok := _u.mutation.QuotaDimension(); ok {
		_spec.SetField(provider.FieldQuotaDimension, field.TypeEnum, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   provider.GroupsTable,
			Columns: provider.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		createE := &ProviderGroupCreate{config: _u.config, mutation: newProviderGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   provider.GroupsTable,
			Columns: provider.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProviderGroupCreate{config: _u.config, mutation: newProviderGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   provider.GroupsTable,
			Columns: provider.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProviderGroupCreate{config: _u.config, mutation: newProviderGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   provider.ProxyTable,
			Columns: []string{provider.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   provider.ProxyTable,
			Columns: []string{provider.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   provider.ParentTable,
			Columns: []string{provider.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   provider.ParentTable,
			Columns: []string{provider.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.ChildrenTable,
			Columns: []string{provider.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.ChildrenTable,
			Columns: []string{provider.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.ChildrenTable,
			Columns: []string{provider.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.UsageLogsTable,
			Columns: []string{provider.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.UsageLogsTable,
			Columns: []string{provider.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.UsageLogsTable,
			Columns: []string{provider.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{provider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderUpdateOne is the builder for updating a single Provider entity.
type ProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderUpdateOne) SetUpdatedAt(v time.Time) *ProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProviderUpdateOne) SetDeletedAt(v time.Time) *ProviderUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableDeletedAt(v *time.Time) *ProviderUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProviderUpdateOne) ClearDeletedAt() *ProviderUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *ProviderUpdateOne) SetName(v string) *ProviderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableName(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ProviderUpdateOne) SetNotes(v string) *ProviderUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableNotes(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ProviderUpdateOne) ClearNotes() *ProviderUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ProviderUpdateOne) SetPlatform(v string) *ProviderUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillablePlatform(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ProviderUpdateOne) SetType(v string) *ProviderUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableType(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetCredentials sets the "credentials" field.
func (_u *ProviderUpdateOne) SetCredentials(v map[string]interface{}) *ProviderUpdateOne {
	_u.mutation.SetCredentials(v)
	return _u
}

// SetExtra sets the "extra" field.
func (_u *ProviderUpdateOne) SetExtra(v map[string]interface{}) *ProviderUpdateOne {
	_u.mutation.SetExtra(v)
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *ProviderUpdateOne) SetProxyID(v int64) *ProviderUpdateOne {
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableProxyID(v *int64) *ProviderUpdateOne {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (_u *ProviderUpdateOne) ClearProxyID() *ProviderUpdateOne {
	_u.mutation.ClearProxyID()
	return _u
}

// SetProxyFallbackOriginID sets the "proxy_fallback_origin_id" field.
func (_u *ProviderUpdateOne) SetProxyFallbackOriginID(v int64) *ProviderUpdateOne {
	_u.mutation.ResetProxyFallbackOriginID()
	_u.mutation.SetProxyFallbackOriginID(v)
	return _u
}

// SetNillableProxyFallbackOriginID sets the "proxy_fallback_origin_id" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableProxyFallbackOriginID(v *int64) *ProviderUpdateOne {
	if v != nil {
		_u.SetProxyFallbackOriginID(*v)
	}
	return _u
}

// AddProxyFallbackOriginID adds value to the "proxy_fallback_origin_id" field.
func (_u *ProviderUpdateOne) AddProxyFallbackOriginID(v int64) *ProviderUpdateOne {
	_u.mutation.AddProxyFallbackOriginID(v)
	return _u
}

// ClearProxyFallbackOriginID clears the value of the "proxy_fallback_origin_id" field.
func (_u *ProviderUpdateOne) ClearProxyFallbackOriginID() *ProviderUpdateOne {
	_u.mutation.ClearProxyFallbackOriginID()
	return _u
}

// SetConcurrency sets the "concurrency" field.
func (_u *ProviderUpdateOne) SetConcurrency(v int) *ProviderUpdateOne {
	_u.mutation.ResetConcurrency()
	_u.mutation.SetConcurrency(v)
	return _u
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableConcurrency(v *int) *ProviderUpdateOne {
	if v != nil {
		_u.SetConcurrency(*v)
	}
	return _u
}

// AddConcurrency adds value to the "concurrency" field.
func (_u *ProviderUpdateOne) AddConcurrency(v int) *ProviderUpdateOne {
	_u.mutation.AddConcurrency(v)
	return _u
}

// SetLoadFactor sets the "load_factor" field.
func (_u *ProviderUpdateOne) SetLoadFactor(v int) *ProviderUpdateOne {
	_u.mutation.ResetLoadFactor()
	_u.mutation.SetLoadFactor(v)
	return _u
}

// SetNillableLoadFactor sets the "load_factor" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableLoadFactor(v *int) *ProviderUpdateOne {
	if v != nil {
		_u.SetLoadFactor(*v)
	}
	return _u
}

// AddLoadFactor adds value to the "load_factor" field.
func (_u *ProviderUpdateOne) AddLoadFactor(v int) *ProviderUpdateOne {
	_u.mutation.AddLoadFactor(v)
	return _u
}

// ClearLoadFactor clears the value of the "load_factor" field.
func (_u *ProviderUpdateOne) ClearLoadFactor() *ProviderUpdateOne {
	_u.mutation.ClearLoadFactor()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ProviderUpdateOne) SetPriority(v int) *ProviderUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillablePriority(v *int) *ProviderUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ProviderUpdateOne) AddPriority(v int) *ProviderUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *ProviderUpdateOne) SetRateMultiplier(v float64) *ProviderUpdateOne {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableRateMultiplier(v *float64) *ProviderUpdateOne {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *ProviderUpdateOne) AddRateMultiplier(v float64) *ProviderUpdateOne {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderUpdateOne) SetStatus(v string) *ProviderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableStatus(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ProviderUpdateOne) SetErrorMessage(v string) *ProviderUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableErrorMessage(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ProviderUpdateOne) ClearErrorMessage() *ProviderUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *ProviderUpdateOne) SetLastUsedAt(v time.Time) *ProviderUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableLastUsedAt(v *time.Time) *ProviderUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *ProviderUpdateOne) ClearLastUsedAt() *ProviderUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ProviderUpdateOne) SetExpiresAt(v time.Time) *ProviderUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableExpiresAt(v *time.Time) *ProviderUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ProviderUpdateOne) ClearExpiresAt() *ProviderUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetAutoPauseOnExpired sets the "auto_pause_on_expired" field.
func (_u *ProviderUpdateOne) SetAutoPauseOnExpired(v bool) *ProviderUpdateOne {
	_u.mutation.SetAutoPauseOnExpired(v)
	return _u
}

// SetNillableAutoPauseOnExpired sets the "auto_pause_on_expired" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableAutoPauseOnExpired(v *bool) *ProviderUpdateOne {
	if v != nil {
		_u.SetAutoPauseOnExpired(*v)
	}
	return _u
}

// SetSchedulable sets the "schedulable" field.
func (_u *ProviderUpdateOne) SetSchedulable(v bool) *ProviderUpdateOne {
	_u.mutation.SetSchedulable(v)
	return _u
}

// SetNillableSchedulable sets the "schedulable" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableSchedulable(v *bool) *ProviderUpdateOne {
	if v != nil {
		_u.SetSchedulable(*v)
	}
	return _u
}

// SetRateLimitedAt sets the "rate_limited_at" field.
func (_u *ProviderUpdateOne) SetRateLimitedAt(v time.Time) *ProviderUpdateOne {
	_u.mutation.SetRateLimitedAt(v)
	return _u
}

// SetNillableRateLimitedAt sets the "rate_limited_at" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableRateLimitedAt(v *time.Time) *ProviderUpdateOne {
	if v != nil {
		_u.SetRateLimitedAt(*v)
	}
	return _u
}

// ClearRateLimitedAt clears the value of the "rate_limited_at" field.
func (_u *ProviderUpdateOne) ClearRateLimitedAt() *ProviderUpdateOne {
	_u.mutation.ClearRateLimitedAt()
	return _u
}

// SetRateLimitResetAt sets the "rate_limit_reset_at" field.
func (_u *ProviderUpdateOne) SetRateLimitResetAt(v time.Time) *ProviderUpdateOne {
	_u.mutation.SetRateLimitResetAt(v)
	return _u
}

// SetNillableRateLimitResetAt sets the "rate_limit_reset_at" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableRateLimitResetAt(v *time.Time) *ProviderUpdateOne {
	if v != nil {
		_u.SetRateLimitResetAt(*v)
	}
	return _u
}

// ClearRateLimitResetAt clears the value of the "rate_limit_reset_at" field.
func (_u *ProviderUpdateOne) ClearRateLimitResetAt() *ProviderUpdateOne {
	_u.mutation.ClearRateLimitResetAt()
	return _u
}

// SetOverloadUntil sets the "overload_until" field.
func (_u *ProviderUpdateOne) SetOverloadUntil(v time.Time) *ProviderUpdateOne {
	_u.mutation.SetOverloadUntil(v)
	return _u
}

// SetNillableOverloadUntil sets the "overload_until" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableOverloadUntil(v *time.Time) *ProviderUpdateOne {
	if v != nil {
		_u.SetOverloadUntil(*v)
	}
	return _u
}

// ClearOverloadUntil clears the value of the "overload_until" field.
func (_u *ProviderUpdateOne) ClearOverloadUntil() *ProviderUpdateOne {
	_u.mutation.ClearOverloadUntil()
	return _u
}

// SetTempUnschedulableUntil sets the "temp_unschedulable_until" field.
func (_u *ProviderUpdateOne) SetTempUnschedulableUntil(v time.Time) *ProviderUpdateOne {
	_u.mutation.SetTempUnschedulableUntil(v)
	return _u
}

// SetNillableTempUnschedulableUntil sets the "temp_unschedulable_until" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableTempUnschedulableUntil(v *time.Time) *ProviderUpdateOne {
	if v != nil {
		_u.SetTempUnschedulableUntil(*v)
	}
	return _u
}

// ClearTempUnschedulableUntil clears the value of the "temp_unschedulable_until" field.
func (_u *ProviderUpdateOne) ClearTempUnschedulableUntil() *ProviderUpdateOne {
	_u.mutation.ClearTempUnschedulableUntil()
	return _u
}

// SetTempUnschedulableReason sets the "temp_unschedulable_reason" field.
func (_u *ProviderUpdateOne) SetTempUnschedulableReason(v string) *ProviderUpdateOne {
	_u.mutation.SetTempUnschedulableReason(v)
	return _u
}

// SetNillableTempUnschedulableReason sets the "temp_unschedulable_reason" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableTempUnschedulableReason(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetTempUnschedulableReason(*v)
	}
	return _u
}

// ClearTempUnschedulableReason clears the value of the "temp_unschedulable_reason" field.
func (_u *ProviderUpdateOne) ClearTempUnschedulableReason() *ProviderUpdateOne {
	_u.mutation.ClearTempUnschedulableReason()
	return _u
}

// SetSessionWindowStart sets the "session_window_start" field.
func (_u *ProviderUpdateOne) SetSessionWindowStart(v time.Time) *ProviderUpdateOne {
	_u.mutation.SetSessionWindowStart(v)
	return _u
}

// SetNillableSessionWindowStart sets the "session_window_start" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableSessionWindowStart(v *time.Time) *ProviderUpdateOne {
	if v != nil {
		_u.SetSessionWindowStart(*v)
	}
	return _u
}

// ClearSessionWindowStart clears the value of the "session_window_start" field.
func (_u *ProviderUpdateOne) ClearSessionWindowStart() *ProviderUpdateOne {
	_u.mutation.ClearSessionWindowStart()
	return _u
}

// SetSessionWindowEnd sets the "session_window_end" field.
func (_u *ProviderUpdateOne) SetSessionWindowEnd(v time.Time) *ProviderUpdateOne {
	_u.mutation.SetSessionWindowEnd(v)
	return _u
}

// SetNillableSessionWindowEnd sets the "session_window_end" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableSessionWindowEnd(v *time.Time) *ProviderUpdateOne {
	if v != nil {
		_u.SetSessionWindowEnd(*v)
	}
	return _u
}

// ClearSessionWindowEnd clears the value of the "session_window_end" field.
func (_u *ProviderUpdateOne) ClearSessionWindowEnd() *ProviderUpdateOne {
	_u.mutation.ClearSessionWindowEnd()
	return _u
}

// SetSessionWindowStatus sets the "session_window_status" field.
func (_u *ProviderUpdateOne) SetSessionWindowStatus(v string) *ProviderUpdateOne {
	_u.mutation.SetSessionWindowStatus(v)
	return _u
}

// SetNillableSessionWindowStatus sets the "session_window_status" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableSessionWindowStatus(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetSessionWindowStatus(*v)
	}
	return _u
}

// ClearSessionWindowStatus clears the value of the "session_window_status" field.
func (_u *ProviderUpdateOne) ClearSessionWindowStatus() *ProviderUpdateOne {
	_u.mutation.ClearSessionWindowStatus()
	return _u
}

// SetParentProviderID sets the "parent_provider_id" field.
func (_u *ProviderUpdateOne) SetParentProviderID(v int64) *ProviderUpdateOne {
	_u.mutation.SetParentProviderID(v)
	return _u
}

// SetNillableParentProviderID sets the "parent_provider_id" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableParentProviderID(v *int64) *ProviderUpdateOne {
	if v != nil {
		_u.SetParentProviderID(*v)
	}
	return _u
}

// ClearParentProviderID clears the value of the "parent_provider_id" field.
func (_u *ProviderUpdateOne) ClearParentProviderID() *ProviderUpdateOne {
	_u.mutation.ClearParentProviderID()
	return _u
}

// SetQuotaDimension sets the "quota_dimension" field.
func (_u *ProviderUpdateOne) SetQuotaDimension(v provider.QuotaDimension) *ProviderUpdateOne {
	_u.mutation.SetQuotaDimension(v)
	return _u
}

// SetNillableQuotaDimension sets the "quota_dimension" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableQuotaDimension(v *provider.QuotaDimension) *ProviderUpdateOne {
	if v != nil {
		_u.SetQuotaDimension(*v)
	}
	return _u
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *ProviderUpdateOne) AddGroupIDs(ids ...int64) *ProviderUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *ProviderUpdateOne) AddGroups(v ...*Group) *ProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_u *ProviderUpdateOne) SetProxy(v *Proxy) *ProviderUpdateOne {
	return _u.SetProxyID(v.ID)
}

// SetParentID sets the "parent" edge to the Provider entity by ID.
func (_u *ProviderUpdateOne) SetParentID(id int64) *ProviderUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Provider entity by ID if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableParentID(id *int64) *ProviderUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Provider entity.
func (_u *ProviderUpdateOne) SetParent(v *Provider) *ProviderUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Provider entity by IDs.
func (_u *ProviderUpdateOne) AddChildIDs(ids ...int64) *ProviderUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Provider entity.
func (_u *ProviderUpdateOne) AddChildren(v ...*Provider) *ProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *ProviderUpdateOne) AddUsageLogIDs(ids ...int64) *ProviderUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *ProviderUpdateOne) AddUsageLogs(v ...*UsageLog) *ProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the ProviderMutation object of the builder.
func (_u *ProviderUpdateOne) Mutation() *ProviderMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *ProviderUpdateOne) ClearGroups() *ProviderUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *ProviderUpdateOne) RemoveGroupIDs(ids ...int64) *ProviderUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *ProviderUpdateOne) RemoveGroups(v ...*Group) *ProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (_u *ProviderUpdateOne) ClearProxy() *ProviderUpdateOne {
	_u.mutation.ClearProxy()
	return _u
}

// ClearParent clears the "parent" edge to the Provider entity.
func (_u *ProviderUpdateOne) ClearParent() *ProviderUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Provider entity.
func (_u *ProviderUpdateOne) ClearChildren() *ProviderUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Provider entities by IDs.
func (_u *ProviderUpdateOne) RemoveChildIDs(ids ...int64) *ProviderUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Provider entities.
func (_u *ProviderUpdateOne) RemoveChildren(v ...*Provider) *ProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *ProviderUpdateOne) ClearUsageLogs() *ProviderUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *ProviderUpdateOne) RemoveUsageLogIDs(ids ...int64) *ProviderUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *ProviderUpdateOne) RemoveUsageLogs(v ...*UsageLog) *ProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the ProviderUpdate builder.
func (_u *ProviderUpdateOne) Where(ps ...predicate.Provider) *ProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderUpdateOne) Select(field string, fields ...string) *ProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Provider entity.
func (_u *ProviderUpdateOne) Save(ctx context.Context) (*Provider, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderUpdateOne) SaveX(ctx context.Context) *Provider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if provider.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized provider.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := provider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := provider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Provider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := provider.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Provider.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := provider.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Provider.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := provider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Provider.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionWindowStatus(); ok {
		if err := provider.SessionWindowStatusValidator(v); err != nil {
			return &ValidationError{Name: "session_window_status", err: fmt.Errorf(`ent: validator failed for field "Provider.session_window_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaDimension(); ok {
		if err := provider.QuotaDimensionValidator(v); err != nil {
			return &ValidationError{Name: "quota_dimension", err: fmt.Errorf(`ent: validator failed for field "Provider.quota_dimension": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderUpdateOne) sqlSave(ctx context.Context) (_node *Provider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(provider.Table, provider.Columns, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Provider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, provider.FieldID)
		for _, f := range fields {
			if !provider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != provider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(provider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(provider.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(provider.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(provider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(provider.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(provider.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(provider.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(provider.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Credentials(); ok {
		_spec.SetField(provider.FieldCredentials, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Extra(); ok {
		_spec.SetField(provider.FieldExtra, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ProxyFallbackOriginID(); ok {
		_spec.SetField(provider.FieldProxyFallbackOriginID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProxyFallbackOriginID(); ok {
		_spec.AddField(provider.FieldProxyFallbackOriginID, field.TypeInt64, value)
	}
	if _u.mutation.ProxyFallbackOriginIDCleared() {
		_spec.ClearField(provider.FieldProxyFallbackOriginID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Concurrency(); ok {
		_spec.SetField(provider.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrency(); ok {
		_spec.AddField(provider.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LoadFactor(); ok {
		_spec.SetField(provider.FieldLoadFactor, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLoadFactor(); ok {
		_spec.AddField(provider.FieldLoadFactor, field.TypeInt, value)
	}
	if _u.mutation.LoadFactorCleared() {
		_spec.ClearField(provider.FieldLoadFactor, field.TypeInt)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(provider.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(provider.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(provider.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(provider.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(provider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(provider.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(provider.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(provider.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(provider.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(provider.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(provider.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AutoPauseOnExpired(); ok {
		_spec.SetField(provider.FieldAutoPauseOnExpired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Schedulable(); ok {
		_spec.SetField(provider.FieldSchedulable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RateLimitedAt(); ok {
		_spec.SetField(provider.FieldRateLimitedAt, field.TypeTime, value)
	}
	if _u.mutation.RateLimitedAtCleared() {
		_spec.ClearField(provider.FieldRateLimitedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RateLimitResetAt(); ok {
		_spec.SetField(provider.FieldRateLimitResetAt, field.TypeTime, value)
	}
	if _u.mutation.RateLimitResetAtCleared() {
		_spec.ClearField(provider.FieldRateLimitResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OverloadUntil(); ok {
		_spec.SetField(provider.FieldOverloadUntil, field.TypeTime, value)
	}
	if _u.mutation.OverloadUntilCleared() {
		_spec.ClearField(provider.FieldOverloadUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.TempUnschedulableUntil(); ok {
		_spec.SetField(provider.FieldTempUnschedulableUntil, field.TypeTime, value)
	}
	if _u.mutation.TempUnschedulableUntilCleared() {
		_spec.ClearField(provider.FieldTempUnschedulableUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.TempUnschedulableReason(); ok {
		_spec.SetField(provider.FieldTempUnschedulableReason, field.TypeString, value)
	}
	if _u.mutation.TempUnschedulableReasonCleared() {
		_spec.ClearField(provider.FieldTempUnschedulableReason, field.TypeString)
	}
	if value, ok := _u.mutation.SessionWindowStart(); ok {
		_spec.SetField(provider.FieldSessionWindowStart, field.TypeTime, value)
	}
	if _u.mutation.SessionWindowStartCleared() {
		_spec.ClearField(provider.FieldSessionWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.SessionWindowEnd(); ok {
		_spec.SetField(provider.FieldSessionWindowEnd, field.TypeTime, value)
	}
	if _u.mutation.SessionWindowEndCleared() {
		_spec.ClearField(provider.FieldSessionWindowEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.SessionWindowStatus(); ok {
		_spec.SetField(provider.FieldSessionWindowStatus, field.TypeString, value)
	}
	if _u.mutation.SessionWindowStatusCleared() {
		_spec.ClearField(provider.FieldSessionWindowStatus, field.TypeString)
	}
	if value, ok := _u.mutation.QuotaDimension(); ok {
		_spec.SetField(provider.FieldQuotaDimension, field.TypeEnum, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   provider.GroupsTable,
			Columns: provider.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		createE := &ProviderGroupCreate{config: _u.config, mutation: newProviderGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   provider.GroupsTable,
			Columns: provider.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProviderGroupCreate{config: _u.config, mutation: newProviderGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   provider.GroupsTable,
			Columns: provider.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProviderGroupCreate{config: _u.config, mutation: newProviderGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   provider.ProxyTable,
			Columns: []string{provider.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   provider.ProxyTable,
			Columns: []string{provider.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   provider.ParentTable,
			Columns: []string{provider.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   provider.ParentTable,
			Columns: []string{provider.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.ChildrenTable,
			Columns: []string{provider.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.ChildrenTable,
			Columns: []string{provider.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.ChildrenTable,
			Columns: []string{provider.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.UsageLogsTable,
			Columns: []string{provider.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.UsageLogsTable,
			Columns: []string{provider.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.UsageLogsTable,
			Columns: []string{provider.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Provider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{provider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
