// Code generated by ent, DO NOT EDIT.

package provider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldName, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldNotes, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldPlatform, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldType, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldProxyID, v))
}

// ProxyFallbackOriginID applies equality check predicate on the "proxy_fallback_origin_id" field. It's identical to ProxyFallbackOriginIDEQ.
func ProxyFallbackOriginID(v int64) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldProxyFallbackOriginID, v))
}

// Concurrency applies equality check predicate on the "concurrency" field. It's identical to ConcurrencyEQ.
func Concurrency(v int) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldConcurrency, v))
}

// LoadFactor applies equality check predicate on the "load_factor" field. It's identical to LoadFactorEQ.
func LoadFactor(v int) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldLoadFactor, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldPriority, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldRateMultiplier, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldStatus, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldErrorMessage, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldLastUsedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldExpiresAt, v))
}

// AutoPauseOnExpired applies equality check predicate on the "auto_pause_on_expired" field. It's identical to AutoPauseOnExpiredEQ.
func AutoPauseOnExpired(v bool) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldAutoPauseOnExpired, v))
}

// Schedulable applies equality check predicate on the "schedulable" field. It's identical to SchedulableEQ.
func Schedulable(v bool) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldSchedulable, v))
}

// RateLimitedAt applies equality check predicate on the "rate_limited_at" field. It's identical to RateLimitedAtEQ.
func RateLimitedAt(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldRateLimitedAt, v))
}

// RateLimitResetAt applies equality check predicate on the "rate_limit_reset_at" field. It's identical to RateLimitResetAtEQ.
func RateLimitResetAt(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldRateLimitResetAt, v))
}

// OverloadUntil applies equality check predicate on the "overload_until" field. It's identical to OverloadUntilEQ.
func OverloadUntil(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldOverloadUntil, v))
}

// TempUnschedulableUntil applies equality check predicate on the "temp_unschedulable_until" field. It's identical to TempUnschedulableUntilEQ.
func TempUnschedulableUntil(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldTempUnschedulableUntil, v))
}

// TempUnschedulableReason applies equality check predicate on the "temp_unschedulable_reason" field. It's identical to TempUnschedulableReasonEQ.
func TempUnschedulableReason(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldTempUnschedulableReason, v))
}

// SessionWindowStart applies equality check predicate on the "session_window_start" field. It's identical to SessionWindowStartEQ.
func SessionWindowStart(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldSessionWindowStart, v))
}

// SessionWindowEnd applies equality check predicate on the "session_window_end" field. It's identical to SessionWindowEndEQ.
func SessionWindowEnd(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldSessionWindowEnd, v))
}

// SessionWindowStatus applies equality check predicate on the "session_window_status" field. It's identical to SessionWindowStatusEQ.
func SessionWindowStatus(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldSessionWindowStatus, v))
}

// ParentProviderID applies equality check predicate on the "parent_provider_id" field. It's identical to ParentProviderIDEQ.
func ParentProviderID(v int64) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldParentProviderID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContainsFold(FieldName, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContainsFold(FieldNotes, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContainsFold(FieldPlatform, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContainsFold(FieldType, v))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProxyIDIsNil applies the IsNil predicate on the "proxy_id" field.
func ProxyIDIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldProxyID))
}

// ProxyIDNotNil applies the NotNil predicate on the "proxy_id" field.
func ProxyIDNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldProxyID))
}

// ProxyFallbackOriginIDEQ applies the EQ predicate on the "proxy_fallback_origin_id" field.
func ProxyFallbackOriginIDEQ(v int64) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldProxyFallbackOriginID, v))
}

// ProxyFallbackOriginIDNEQ applies the NEQ predicate on the "proxy_fallback_origin_id" field.
func ProxyFallbackOriginIDNEQ(v int64) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldProxyFallbackOriginID, v))
}

// ProxyFallbackOriginIDIn applies the In predicate on the "proxy_fallback_origin_id" field.
func ProxyFallbackOriginIDIn(vs ...int64) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldProxyFallbackOriginID, vs...))
}

// ProxyFallbackOriginIDNotIn applies the NotIn predicate on the "proxy_fallback_origin_id" field.
func ProxyFallbackOriginIDNotIn(vs ...int64) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldProxyFallbackOriginID, vs...))
}

// ProxyFallbackOriginIDGT applies the GT predicate on the "proxy_fallback_origin_id" field.
func ProxyFallbackOriginIDGT(v int64) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldProxyFallbackOriginID, v))
}

// ProxyFallbackOriginIDGTE applies the GTE predicate on the "proxy_fallback_origin_id" field.
func ProxyFallbackOriginIDGTE(v int64) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldProxyFallbackOriginID, v))
}

// ProxyFallbackOriginIDLT applies the LT predicate on the "proxy_fallback_origin_id" field.
func ProxyFallbackOriginIDLT(v int64) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldProxyFallbackOriginID, v))
}

// ProxyFallbackOriginIDLTE applies the LTE predicate on the "proxy_fallback_origin_id" field.
func ProxyFallbackOriginIDLTE(v int64) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldProxyFallbackOriginID, v))
}

// ProxyFallbackOriginIDIsNil applies the IsNil predicate on the "proxy_fallback_origin_id" field.
func ProxyFallbackOriginIDIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldProxyFallbackOriginID))
}

// ProxyFallbackOriginIDNotNil applies the NotNil predicate on the "proxy_fallback_origin_id" field.
func ProxyFallbackOriginIDNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldProxyFallbackOriginID))
}

// ConcurrencyEQ applies the EQ predicate on the "concurrency" field.
func ConcurrencyEQ(v int) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldConcurrency, v))
}

// ConcurrencyNEQ applies the NEQ predicate on the "concurrency" field.
func ConcurrencyNEQ(v int) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldConcurrency, v))
}

// ConcurrencyIn applies the In predicate on the "concurrency" field.
func ConcurrencyIn(vs ...int) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldConcurrency, vs...))
}

// ConcurrencyNotIn applies the NotIn predicate on the "concurrency" field.
func ConcurrencyNotIn(vs ...int) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldConcurrency, vs...))
}

// ConcurrencyGT applies the GT predicate on the "concurrency" field.
func ConcurrencyGT(v int) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldConcurrency, v))
}

// ConcurrencyGTE applies the GTE predicate on the "concurrency" field.
func ConcurrencyGTE(v int) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldConcurrency, v))
}

// ConcurrencyLT applies the LT predicate on the "concurrency" field.
func ConcurrencyLT(v int) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldConcurrency, v))
}

// ConcurrencyLTE applies the LTE predicate on the "concurrency" field.
func ConcurrencyLTE(v int) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldConcurrency, v))
}

// LoadFactorEQ applies the EQ predicate on the "load_factor" field.
func LoadFactorEQ(v int) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldLoadFactor, v))
}

// LoadFactorNEQ applies the NEQ predicate on the "load_factor" field.
func LoadFactorNEQ(v int) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldLoadFactor, v))
}

// LoadFactorIn applies the In predicate on the "load_factor" field.
func LoadFactorIn(vs ...int) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldLoadFactor, vs...))
}

// LoadFactorNotIn applies the NotIn predicate on the "load_factor" field.
func LoadFactorNotIn(vs ...int) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldLoadFactor, vs...))
}

// LoadFactorGT applies the GT predicate on the "load_factor" field.
func LoadFactorGT(v int) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldLoadFactor, v))
}

// LoadFactorGTE applies the GTE predicate on the "load_factor" field.
func LoadFactorGTE(v int) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldLoadFactor, v))
}

// LoadFactorLT applies the LT predicate on the "load_factor" field.
func LoadFactorLT(v int) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldLoadFactor, v))
}

// LoadFactorLTE applies the LTE predicate on the "load_factor" field.
func LoadFactorLTE(v int) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldLoadFactor, v))
}

// LoadFactorIsNil applies the IsNil predicate on the "load_factor" field.
func LoadFactorIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldLoadFactor))
}

// LoadFactorNotNil applies the NotNil predicate on the "load_factor" field.
func LoadFactorNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldLoadFactor))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldPriority, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldRateMultiplier, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContainsFold(FieldErrorMessage, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldLastUsedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldExpiresAt))
}

// AutoPauseOnExpiredEQ applies the EQ predicate on the "auto_pause_on_expired" field.
func AutoPauseOnExpiredEQ(v bool) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldAutoPauseOnExpired, v))
}

// AutoPauseOnExpiredNEQ applies the NEQ predicate on the "auto_pause_on_expired" field.
func AutoPauseOnExpiredNEQ(v bool) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldAutoPauseOnExpired, v))
}

// SchedulableEQ applies the EQ predicate on the "schedulable" field.
func SchedulableEQ(v bool) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldSchedulable, v))
}

// SchedulableNEQ applies the NEQ predicate on the "schedulable" field.
func SchedulableNEQ(v bool) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldSchedulable, v))
}

// RateLimitedAtEQ applies the EQ predicate on the "rate_limited_at" field.
func RateLimitedAtEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldRateLimitedAt, v))
}

// RateLimitedAtNEQ applies the NEQ predicate on the "rate_limited_at" field.
func RateLimitedAtNEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldRateLimitedAt, v))
}

// RateLimitedAtIn applies the In predicate on the "rate_limited_at" field.
func RateLimitedAtIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldRateLimitedAt, vs...))
}

// RateLimitedAtNotIn applies the NotIn predicate on the "rate_limited_at" field.
func RateLimitedAtNotIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldRateLimitedAt, vs...))
}

// RateLimitedAtGT applies the GT predicate on the "rate_limited_at" field.
func RateLimitedAtGT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldRateLimitedAt, v))
}

// RateLimitedAtGTE applies the GTE predicate on the "rate_limited_at" field.
func RateLimitedAtGTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldRateLimitedAt, v))
}

// RateLimitedAtLT applies the LT predicate on the "rate_limited_at" field.
func RateLimitedAtLT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldRateLimitedAt, v))
}

// RateLimitedAtLTE applies the LTE predicate on the "rate_limited_at" field.
func RateLimitedAtLTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldRateLimitedAt, v))
}

// RateLimitedAtIsNil applies the IsNil predicate on the "rate_limited_at" field.
func RateLimitedAtIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldRateLimitedAt))
}

// RateLimitedAtNotNil applies the NotNil predicate on the "rate_limited_at" field.
func RateLimitedAtNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldRateLimitedAt))
}

// RateLimitResetAtEQ applies the EQ predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldRateLimitResetAt, v))
}

// RateLimitResetAtNEQ applies the NEQ predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtNEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldRateLimitResetAt, v))
}

// RateLimitResetAtIn applies the In predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldRateLimitResetAt, vs...))
}

// RateLimitResetAtNotIn applies the NotIn predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtNotIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldRateLimitResetAt, vs...))
}

// RateLimitResetAtGT applies the GT predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtGT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldRateLimitResetAt, v))
}

// RateLimitResetAtGTE applies the GTE predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtGTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldRateLimitResetAt, v))
}

// RateLimitResetAtLT applies the LT predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtLT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldRateLimitResetAt, v))
}

// RateLimitResetAtLTE applies the LTE predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtLTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldRateLimitResetAt, v))
}

// RateLimitResetAtIsNil applies the IsNil predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldRateLimitResetAt))
}

// RateLimitResetAtNotNil applies the NotNil predicate on the "rate_limit_reset_at" field.
func RateLimitResetAtNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldRateLimitResetAt))
}

// OverloadUntilEQ applies the EQ predicate on the "overload_until" field.
func OverloadUntilEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldOverloadUntil, v))
}

// OverloadUntilNEQ applies the NEQ predicate on the "overload_until" field.
func OverloadUntilNEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldOverloadUntil, v))
}

// OverloadUntilIn applies the In predicate on the "overload_until" field.
func OverloadUntilIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldOverloadUntil, vs...))
}

// OverloadUntilNotIn applies the NotIn predicate on the "overload_until" field.
func OverloadUntilNotIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldOverloadUntil, vs...))
}

// OverloadUntilGT applies the GT predicate on the "overload_until" field.
func OverloadUntilGT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldOverloadUntil, v))
}

// OverloadUntilGTE applies the GTE predicate on the "overload_until" field.
func OverloadUntilGTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldOverloadUntil, v))
}

// OverloadUntilLT applies the LT predicate on the "overload_until" field.
func OverloadUntilLT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldOverloadUntil, v))
}

// OverloadUntilLTE applies the LTE predicate on the "overload_until" field.
func OverloadUntilLTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldOverloadUntil, v))
}

// OverloadUntilIsNil applies the IsNil predicate on the "overload_until" field.
func OverloadUntilIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldOverloadUntil))
}

// OverloadUntilNotNil applies the NotNil predicate on the "overload_until" field.
func OverloadUntilNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldOverloadUntil))
}

// TempUnschedulableUntilEQ applies the EQ predicate on the "temp_unschedulable_until" field.
func TempUnschedulableUntilEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldTempUnschedulableUntil, v))
}

// TempUnschedulableUntilNEQ applies the NEQ predicate on the "temp_unschedulable_until" field.
func TempUnschedulableUntilNEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldTempUnschedulableUntil, v))
}

// TempUnschedulableUntilIn applies the In predicate on the "temp_unschedulable_until" field.
func TempUnschedulableUntilIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldTempUnschedulableUntil, vs...))
}

// TempUnschedulableUntilNotIn applies the NotIn predicate on the "temp_unschedulable_until" field.
func TempUnschedulableUntilNotIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldTempUnschedulableUntil, vs...))
}

// TempUnschedulableUntilGT applies the GT predicate on the "temp_unschedulable_until" field.
func TempUnschedulableUntilGT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldTempUnschedulableUntil, v))
}

// TempUnschedulableUntilGTE applies the GTE predicate on the "temp_unschedulable_until" field.
func TempUnschedulableUntilGTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldTempUnschedulableUntil, v))
}

// TempUnschedulableUntilLT applies the LT predicate on the "temp_unschedulable_until" field.
func TempUnschedulableUntilLT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldTempUnschedulableUntil, v))
}

// TempUnschedulableUntilLTE applies the LTE predicate on the "temp_unschedulable_until" field.
func TempUnschedulableUntilLTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldTempUnschedulableUntil, v))
}

// TempUnschedulableUntilIsNil applies the IsNil predicate on the "temp_unschedulable_until" field.
func TempUnschedulableUntilIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldTempUnschedulableUntil))
}

// TempUnschedulableUntilNotNil applies the NotNil predicate on the "temp_unschedulable_until" field.
func TempUnschedulableUntilNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldTempUnschedulableUntil))
}

// TempUnschedulableReasonEQ applies the EQ predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldTempUnschedulableReason, v))
}

// TempUnschedulableReasonNEQ applies the NEQ predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonNEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldTempUnschedulableReason, v))
}

// TempUnschedulableReasonIn applies the In predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldTempUnschedulableReason, vs...))
}

// TempUnschedulableReasonNotIn applies the NotIn predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonNotIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldTempUnschedulableReason, vs...))
}

// TempUnschedulableReasonGT applies the GT predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonGT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldTempUnschedulableReason, v))
}

// TempUnschedulableReasonGTE applies the GTE predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonGTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldTempUnschedulableReason, v))
}

// TempUnschedulableReasonLT applies the LT predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonLT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldTempUnschedulableReason, v))
}

// TempUnschedulableReasonLTE applies the LTE predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonLTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldTempUnschedulableReason, v))
}

// TempUnschedulableReasonContains applies the Contains predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonContains(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContains(FieldTempUnschedulableReason, v))
}

// TempUnschedulableReasonHasPrefix applies the HasPrefix predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonHasPrefix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasPrefix(FieldTempUnschedulableReason, v))
}

// TempUnschedulableReasonHasSuffix applies the HasSuffix predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonHasSuffix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasSuffix(FieldTempUnschedulableReason, v))
}

// TempUnschedulableReasonIsNil applies the IsNil predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldTempUnschedulableReason))
}

// TempUnschedulableReasonNotNil applies the NotNil predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldTempUnschedulableReason))
}

// TempUnschedulableReasonEqualFold applies the EqualFold predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonEqualFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEqualFold(FieldTempUnschedulableReason, v))
}

// TempUnschedulableReasonContainsFold applies the ContainsFold predicate on the "temp_unschedulable_reason" field.
func TempUnschedulableReasonContainsFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContainsFold(FieldTempUnschedulableReason, v))
}

// SessionWindowStartEQ applies the EQ predicate on the "session_window_start" field.
func SessionWindowStartEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldSessionWindowStart, v))
}

// SessionWindowStartNEQ applies the NEQ predicate on the "session_window_start" field.
func SessionWindowStartNEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldSessionWindowStart, v))
}

// SessionWindowStartIn applies the In predicate on the "session_window_start" field.
func SessionWindowStartIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldSessionWindowStart, vs...))
}

// SessionWindowStartNotIn applies the NotIn predicate on the "session_window_start" field.
func SessionWindowStartNotIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldSessionWindowStart, vs...))
}

// SessionWindowStartGT applies the GT predicate on the "session_window_start" field.
func SessionWindowStartGT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldSessionWindowStart, v))
}

// SessionWindowStartGTE applies the GTE predicate on the "session_window_start" field.
func SessionWindowStartGTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldSessionWindowStart, v))
}

// SessionWindowStartLT applies the LT predicate on the "session_window_start" field.
func SessionWindowStartLT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldSessionWindowStart, v))
}

// SessionWindowStartLTE applies the LTE predicate on the "session_window_start" field.
func SessionWindowStartLTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldSessionWindowStart, v))
}

// SessionWindowStartIsNil applies the IsNil predicate on the "session_window_start" field.
func SessionWindowStartIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldSessionWindowStart))
}

// SessionWindowStartNotNil applies the NotNil predicate on the "session_window_start" field.
func SessionWindowStartNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldSessionWindowStart))
}

// SessionWindowEndEQ applies the EQ predicate on the "session_window_end" field.
func SessionWindowEndEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldSessionWindowEnd, v))
}

// SessionWindowEndNEQ applies the NEQ predicate on the "session_window_end" field.
func SessionWindowEndNEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldSessionWindowEnd, v))
}

// SessionWindowEndIn applies the In predicate on the "session_window_end" field.
func SessionWindowEndIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldSessionWindowEnd, vs...))
}

// SessionWindowEndNotIn applies the NotIn predicate on the "session_window_end" field.
func SessionWindowEndNotIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldSessionWindowEnd, vs...))
}

// SessionWindowEndGT applies the GT predicate on the "session_window_end" field.
func SessionWindowEndGT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldSessionWindowEnd, v))
}

// SessionWindowEndGTE applies the GTE predicate on the "session_window_end" field.
func SessionWindowEndGTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldSessionWindowEnd, v))
}

// SessionWindowEndLT applies the LT predicate on the "session_window_end" field.
func SessionWindowEndLT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldSessionWindowEnd, v))
}

// SessionWindowEndLTE applies the LTE predicate on the "session_window_end" field.
func SessionWindowEndLTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldSessionWindowEnd, v))
}

// SessionWindowEndIsNil applies the IsNil predicate on the "session_window_end" field.
func SessionWindowEndIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldSessionWindowEnd))
}

// SessionWindowEndNotNil applies the NotNil predicate on the "session_window_end" field.
func SessionWindowEndNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldSessionWindowEnd))
}

// SessionWindowStatusEQ applies the EQ predicate on the "session_window_status" field.
func SessionWindowStatusEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldSessionWindowStatus, v))
}

// SessionWindowStatusNEQ applies the NEQ predicate on the "session_window_status" field.
func SessionWindowStatusNEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldSessionWindowStatus, v))
}

// SessionWindowStatusIn applies the In predicate on the "session_window_status" field.
func SessionWindowStatusIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldSessionWindowStatus, vs...))
}

// SessionWindowStatusNotIn applies the NotIn predicate on the "session_window_status" field.
func SessionWindowStatusNotIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldSessionWindowStatus, vs...))
}

// SessionWindowStatusGT applies the GT predicate on the "session_window_status" field.
func SessionWindowStatusGT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldSessionWindowStatus, v))
}

// SessionWindowStatusGTE applies the GTE predicate on the "session_window_status" field.
func SessionWindowStatusGTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldSessionWindowStatus, v))
}

// SessionWindowStatusLT applies the LT predicate on the "session_window_status" field.
func SessionWindowStatusLT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldSessionWindowStatus, v))
}

// SessionWindowStatusLTE applies the LTE predicate on the "session_window_status" field.
func SessionWindowStatusLTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldSessionWindowStatus, v))
}

// SessionWindowStatusContains applies the Contains predicate on the "session_window_status" field.
func SessionWindowStatusContains(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContains(FieldSessionWindowStatus, v))
}

// SessionWindowStatusHasPrefix applies the HasPrefix predicate on the "session_window_status" field.
func SessionWindowStatusHasPrefix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasPrefix(FieldSessionWindowStatus, v))
}

// SessionWindowStatusHasSuffix applies the HasSuffix predicate on the "session_window_status" field.
func SessionWindowStatusHasSuffix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasSuffix(FieldSessionWindowStatus, v))
}

// SessionWindowStatusIsNil applies the IsNil predicate on the "session_window_status" field.
func SessionWindowStatusIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldSessionWindowStatus))
}

// SessionWindowStatusNotNil applies the NotNil predicate on the "session_window_status" field.
func SessionWindowStatusNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldSessionWindowStatus))
}

// SessionWindowStatusEqualFold applies the EqualFold predicate on the "session_window_status" field.
func SessionWindowStatusEqualFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEqualFold(FieldSessionWindowStatus, v))
}

// SessionWindowStatusContainsFold applies the ContainsFold predicate on the "session_window_status" field.
func SessionWindowStatusContainsFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContainsFold(FieldSessionWindowStatus, v))
}

// ParentProviderIDEQ applies the EQ predicate on the "parent_provider_id" field.
func ParentProviderIDEQ(v int64) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldParentProviderID, v))
}

// ParentProviderIDNEQ applies the NEQ predicate on the "parent_provider_id" field.
func ParentProviderIDNEQ(v int64) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldParentProviderID, v))
}

// ParentProviderIDIn applies the In predicate on the "parent_provider_id" field.
func ParentProviderIDIn(vs ...int64) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldParentProviderID, vs...))
}

// ParentProviderIDNotIn applies the NotIn predicate on the "parent_provider_id" field.
func ParentProviderIDNotIn(vs ...int64) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldParentProviderID, vs...))
}

// ParentProviderIDIsNil applies the IsNil predicate on the "parent_provider_id" field.
func ParentProviderIDIsNil() predicate.Provider {
	return predicate.Provider(sql.FieldIsNull(FieldParentProviderID))
}

// ParentProviderIDNotNil applies the NotNil predicate on the "parent_provider_id" field.
func ParentProviderIDNotNil() predicate.Provider {
	return predicate.Provider(sql.FieldNotNull(FieldParentProviderID))
}

// QuotaDimensionEQ applies the EQ predicate on the "quota_dimension" field.
func QuotaDimensionEQ(v QuotaDimension) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldQuotaDimension, v))
}

// QuotaDimensionNEQ applies the NEQ predicate on the "quota_dimension" field.
func QuotaDimensionNEQ(v QuotaDimension) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldQuotaDimension, v))
}

// QuotaDimensionIn applies the In predicate on the "quota_dimension" field.
func QuotaDimensionIn(vs ...QuotaDimension) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldQuotaDimension, vs...))
}

// QuotaDimensionNotIn applies the NotIn predicate on the "quota_dimension" field.
func QuotaDimensionNotIn(vs ...QuotaDimension) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldQuotaDimension, vs...))
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, GroupsTable, GroupsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.Group) predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProxy applies the HasEdge predicate on the "proxy" edge.
func HasProxy() predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProxyTable, ProxyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProxyWith applies the HasEdge predicate on the "proxy" edge with a given conditions (other predicates).
func HasProxyWith(preds ...predicate.Proxy) predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := newProxyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParent applies the HasEdge predicate on the "parent" edge.
func HasParent() predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentWith applies the HasEdge predicate on the "parent" edge with a given conditions (other predicates).
func HasParentWith(preds ...predicate.Provider) predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := newParentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChildren applies the HasEdge predicate on the "children" edge.
func HasChildren() predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildrenWith applies the HasEdge predicate on the "children" edge with a given conditions (other predicates).
func HasChildrenWith(preds ...predicate.Provider) predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := newChildrenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProviderGroups applies the HasEdge predicate on the "provider_groups" edge.
func HasProviderGroups() predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ProviderGroupsTable, ProviderGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderGroupsWith applies the HasEdge predicate on the "provider_groups" edge with a given conditions (other predicates).
func HasProviderGroupsWith(preds ...predicate.ProviderGroup) predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := newProviderGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Provider) predicate.Provider {
	return predicate.Provider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Provider) predicate.Provider {
	return predicate.Provider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Provider) predicate.Provider {
	return predicate.Provider(sql.NotPredicates(p))
}
