import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import Editor from '../CodexTicketProxyEditor.vue'
import Select from '@/components/common/Select.vue'
const { getAll, testProxy } = vi.hoisted(() => ({ getAll: vi.fn(), testProxy: vi.fn() }))
vi.mock('@/api/admin/proxies', () => ({ getAll }))
vi.mock('@/api/admin/codexTickets', () => ({ testTicketProxy: testProxy }))
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key, locale: { value: 'zh' } }) }))
describe('采集代理来源', () => {
  beforeEach(() => { vi.clearAllMocks(); getAll.mockResolvedValue([{ id: 9, name: 'TW', host: 'proxy.invalid', port: 8080 }]) })
  it('默认关闭；只在轮换/动态显示，显式修改才写入，继承不覆盖网关策略', async () => {
    const w = mount(Editor, { props: { allowInherit: true, value: { mode: 'fixed', dynamic_source: 'template', proxy_protocol: 'http', extraction_configured: false, fixed_proxy_id: 'one', proxies: [{ id: 'one', name: 'A', configured: true }] } } })
    await flushPromises()
    expect(w.find('[data-testid="ticket-proxy-reuse-setting"]').exists()).toBe(false)
    w.findAllComponents(Select)[0].vm.$emit('update:modelValue', 'rotate')
    await flushPromises()
    expect(w.get('[data-testid="ticket-proxy-reuse-toggle"]').attributes('aria-checked')).toBe('false')
    await w.get('[data-testid="ticket-proxy-reuse-toggle"]').trigger('click')
    expect((w.vm as unknown as { patch: () => unknown }).patch()).toMatchObject({ mode: 'rotate', reuse_successful_ip: true })
    await w.setProps({ locked: true })
    expect(w.get('[data-testid="ticket-proxy-reuse-toggle"]').attributes('disabled')).toBeDefined()
    await w.setProps({ locked: false })
    w.findAllComponents(Select)[0].vm.$emit('update:modelValue', 'inherit')
    await flushPromises()
    expect(w.find('[data-testid="ticket-proxy-reuse-setting"]').exists()).toBe(false)
    expect((w.vm as unknown as { patch: () => unknown }).patch()).toEqual({ mode: 'inherit' })
    w.unmount()
  })
  it('动态API复用开关回填并随代理保存；换账号不沿用旧开关', async () => {
    const value = { mode: 'dynamic' as const, dynamic_source: 'api' as const, proxy_protocol: 'http' as const, extraction_configured: true, fixed_proxy_id: '', proxies: [], reuse_successful_ip: true }
    const w = mount(Editor, { props: { value } })
    await flushPromises()
    expect(w.get('[data-testid="ticket-proxy-reuse-toggle"]').attributes('aria-checked')).toBe('true')
    expect((w.vm as unknown as { patch: () => unknown }).patch()).toMatchObject({ mode: 'dynamic', reuse_successful_ip: true })
    await w.setProps({ value: { ...value, reuse_successful_ip: false } })
    expect(w.get('[data-testid="ticket-proxy-reuse-toggle"]').attributes('aria-checked')).toBe('false')
    w.unmount()
  })
  it('打开已有管理代理就加载选项，轮换可同时使用管理代理与手填地址', async () => {
    const w = mount(Editor, { props: { value: { mode: 'rotate', dynamic_source: 'template', proxy_protocol: 'http', extraction_configured: false, fixed_proxy_id: 'managed', proxies: [{ id: 'managed', name: 'TW', configured: true, managed_proxy_id: 9 }, { id: 'manual', name: 'Manual', configured: true }] } } })
    await flushPromises()
    expect(getAll).toHaveBeenCalledOnce()
    expect(w.findAllComponents(Select).some(s => s.props('options').some(o => o.value === 9))).toBe(true)
    await w.get('[data-testid="ticket-proxy-url"]').setValue('socks5h://user:synthetic@manual.invalid:1080')
    const patch = (w.vm as unknown as { patch: () => unknown }).patch()
    expect(patch).toMatchObject({ mode: 'rotate', proxies: [{ managed_proxy_id: 9, harvest_proxy_url: '' }, { harvest_proxy_url: 'socks5h://user:synthetic@manual.invalid:1080' }] })
    expect(testProxy).not.toHaveBeenCalled()
    w.unmount()
  })
})
