import { flushPromises, mount, type VueWrapper } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import CodexTicketAccountSettings from '../CodexTicketAccountSettings.vue'
import Select from '@/components/common/Select.vue'
import ProxyEditor from '../CodexTicketProxyEditor.vue'

const { get, update, defaults, updateDefaults, testProxy } = vi.hoisted(() => ({ get: vi.fn(), update: vi.fn(), defaults:vi.fn(),updateDefaults:vi.fn(),testProxy: vi.fn() }))
vi.mock('@/api/admin/codexTickets', () => ({ ticketAccountAPI: { get, update, defaults, updateDefaults }, testTicketProxy: testProxy }))
vi.mock('@/api/admin/proxies',()=>({getAll:vi.fn().mockResolvedValue([])}))
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
const rules = () => ({ models: ['gpt-6-astra', 'gpt-5.6-sol'], target_length: 332, degraded_signal_length: 312, max_attempts: 3, concurrency: 4, cache_minutes: 60, refresh_before_minutes: 10, retry_interval_seconds: 1, probe_interval_seconds: 6, failure_threshold: 0, cooldown_seconds: 300 })
const account = () => ({ verified_flow: false, rules: rules(), proxy_policy: { mode: 'fixed', dynamic_source: 'template', proxy_protocol: 'http', extraction_configured: false, fixed_proxy_id: 'account', proxies: [{ id: 'account', name: 'A', configured: true }] }, account_id: 1, mode: 'inherit', watchdog_mode: 'observe', effective_watchdog_mode: 'observe', effective_enabled: true, proxy_source: 'account', proxy_configured: true, revision: 'r1' })

// 父表单先准备快照，再使用原保存按钮提交；组件不再渲染独立保存按钮。
async function save(w: VueWrapper) {
  const commit = await (w.vm as unknown as { prepareSave: () => Promise<(() => Promise<void>) | undefined> }).prepareSave()
  await commit?.()
  await flushPromises()
}
const flow = (w: VueWrapper) => w.findAllComponents(Select).find(c => c.attributes('data-testid') === 'ticket-verified-flow')!
const guardSelect = (w: VueWrapper) => w.findAllComponents(Select).find(c => c.attributes('data-testid') === 'ticket-guard')!

describe('CodexTicketAccountSettings', () => {
  it('批量账号已开双链路，未勾选修改双链路也锁定有效守护；明确关闭后恢复', async () => {
    get.mockResolvedValue({ ...account(), verified_flow: true, watchdog_mode: 'off' })
    const w=mount(CodexTicketAccountSettings,{attachTo:document.body,props:{ids:[1,2],bulk:true}})
    await flushPromises()
    await w.get('[data-testid="ticket-edit-mode"]').setValue(true)
    expect(guardSelect(w).props('modelValue')).toBe('recover')
    expect(guardSelect(w).props('disabled')).toBe(true)
    expect(w.get('[data-testid="ticket-edit-guard"]').attributes('disabled')).toBeDefined()
    await w.get('[data-testid="ticket-edit-flow"]').setValue(true)
    flow(w).vm.$emit('update:modelValue','false');await flushPromises()
    expect(guardSelect(w).props('modelValue')).toBe('off')
    await w.get('[data-testid="ticket-edit-guard"]').setValue(true)
    expect(guardSelect(w).props('disabled')).toBe(false)
    expect(guardSelect(w).props('options').some((option: {value:string})=>option.value==='inherit')).toBe(false)
    w.unmount()
  })
  it('批量混合双链路状态时不提供会被部分账号忽略的守护选择', async () => {
    get.mockImplementation(async id=>({...account(),verified_flow:id===1}))
    const w=mount(CodexTicketAccountSettings,{props:{ids:[1,2],bulk:true}});await flushPromises()
    await w.get('[data-testid="ticket-edit-mode"]').setValue(true)
    expect(guardSelect(w).props('disabled')).toBe(true)
    w.unmount()
  })
  beforeEach(() => { vi.clearAllMocks(); get.mockResolvedValue(account()); defaults.mockResolvedValue(account()); updateDefaults.mockResolvedValue(account());update.mockResolvedValue([{ ...account(), revision: 'r2' }]) })
  it('批量恢复整张卡片与规则分组，虚实勾选不改提交范围', async () => {
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { ids: [1, 2], bulk: true } })
    await flushPromises()
    expect(w.attributes('style')).toContain('box-shadow')
    expect(w.findAll('[data-testid^="ticket-group-"]')).toHaveLength(3)
    expect(w.get('[data-testid="ticket-workbench-body"]').isVisible()).toBe(false)
    await w.get('[data-testid="ticket-edit-mode"]').setValue(true)
    await flushPromises()
    expect(w.get('[data-testid="ticket-workbench-body"]').isVisible()).toBe(true)
    const value = w.get('[data-testid="ticket-rule-target_length"]')
    expect(value.classes()).toContain('opacity-50')
    expect(value.attributes('disabled')).toBeDefined()
    await w.get('[data-testid="ticket-edit-target_length"]').setValue(true)
    expect(value.classes()).not.toContain('opacity-50')
    expect(value.attributes('disabled')).toBeUndefined()
    await value.setValue('356')
    await w.get('[data-testid="ticket-edit-target_length"]').setValue(false)
    expect(value.classes()).toContain('opacity-50')
    expect((w.vm as unknown as { patch: () => unknown }).patch()).toEqual({ mode: 'on' })
    for (const key of ['guard', 'flow', 'proxy']) {
      const body = w.get(`[data-testid="ticket-bulk-body-${key}"]`)
      expect(body.classes()).toContain('opacity-50')
      await w.get(`[data-testid="ticket-edit-${key}"]`).setValue(true)
      expect(body.classes()).not.toContain('opacity-50')
      await w.get(`[data-testid="ticket-edit-${key}"]`).setValue(false)
    }
    expect(w.get('[data-testid="ticket-proxy-test"]').attributes('disabled')).toBeDefined()
    expect(testProxy).not.toHaveBeenCalled()
    w.unmount()
    const single = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { ids: [1] } })
    await flushPromises()
    expect(single.classes()).toContain('border-2')
    expect(single.attributes('style')).toContain('box-shadow')
    single.unmount()
  })
  it('新号等待模板加载，加载失败不能提交内置值', async () => {
    let finish!: (value: ReturnType<typeof account>) => void
    defaults.mockReturnValue(new Promise(resolve => { finish = resolve }))
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { draft: true } })
    const vm = w.vm as unknown as { patch: () => unknown; ensureReady: () => Promise<void> }
    expect(() => vm.patch()).toThrow()
    let ready = false
    const waiting = vm.ensureReady().then(() => { ready = true })
    await flushPromises()
    expect(ready).toBe(false)
    finish(account())
    await waiting
    expect(vm.patch()).toMatchObject({ rules: { target_length: 332 } })
    w.unmount()
    defaults.mockRejectedValue(new Error('offline'))
    const failed = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { draft: true } })
    await flushPromises()
    expect(() => (failed.vm as unknown as { patch: () => unknown }).patch()).toThrow()
    failed.unmount()
  })
  it('空模板新增手填代理使用当前草稿，不被自动继承覆盖', async () => {
    defaults.mockResolvedValue({ ...account(), proxy_source: 'gateway', proxy_policy: { ...account().proxy_policy, proxies: [], fixed_proxy_id: '' } })
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { draft: true } })
    await flushPromises()
    await w.get('[data-testid="ticket-edit-proxy"]').setValue(true)
    const editor = w.findComponent(ProxyEditor)
    editor.findAllComponents(Select)[0].vm.$emit('update:modelValue', 'fixed')
    await flushPromises()
    await editor.findAll('button').find(b => b.text() === 'admin.settings.codexTicket.addProxy')!.trigger('click')
    await editor.get('[data-testid="ticket-proxy-url"]').setValue('http://user:synthetic@proxy.invalid:8080')
    expect((w.vm as unknown as { patch: () => unknown }).patch()).toMatchObject({ proxy_policy: { mode: 'fixed', proxies: [{ harvest_proxy_url: 'http://user:synthetic@proxy.invalid:8080' }] } })
    w.unmount()
  })
  it('批量读取相同332，差异字段留空且未勾选不提交', async()=>{
    get.mockImplementation(async(id:number)=>({...account(),account_id:id,rules:{...rules(),max_attempts:id===1?0:3}}))
    const w=mount(CodexTicketAccountSettings,{props:{ids:[1,2],bulk:true}});await flushPromises()
    expect((w.get('[data-testid="ticket-rule-target_length"]').element as HTMLInputElement).value).toBe('332')
    expect((w.get('[data-testid="ticket-rule-max_attempts"]').element as HTMLInputElement).value).toBe('')
    await w.get('[data-testid="ticket-edit-mode"]').setValue(true)
    await save(w);await flushPromises()
    expect(update.mock.calls[0][1]).toEqual({mode:'on'});w.unmount()
  })
  it('默认模板和新增草稿读取同一配置，草稿不直接写账号', async()=>{
    const w=mount(CodexTicketAccountSettings,{props:{draft:true}});await flushPromises()
    expect(defaults).toHaveBeenCalled();expect(get).not.toHaveBeenCalled()
    expect(w.find('[data-testid="ticket-account-save"]').exists()).toBe(false)
    expect((w.vm as unknown as {patch:()=>{rules:{target_length:number}}}).patch().rules.target_length).toBe(332)
    expect(update).not.toHaveBeenCalled();w.unmount()
    const template=mount(CodexTicketAccountSettings,{props:{templateMode:true}});await flushPromises()
    await template.get('[data-testid="ticket-rule-max_attempts"]').setValue('5');await save(template);await flushPromises()
    expect(updateDefaults).toHaveBeenCalledWith(expect.objectContaining({rules:expect.objectContaining({target_length:332,max_attempts:5})}),'r1');template.unmount()
  })
  it('双链路默认关闭；批量必须勾选才提交，且不覆盖旧守护选择', async () => {
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { ids: [1, 2], bulk: true } }); await flushPromises()
    await w.get('[data-testid="ticket-edit-mode"]').setValue(true)
    expect(flow(w).props('modelValue')).toBe('false')
    expect(flow(w).props('disabled')).toBe(true)
    await w.get('[data-testid="ticket-edit-flow"]').setValue(true)
    flow(w).vm.$emit('update:modelValue','true');await flushPromises()
    await save(w); await flushPromises()
    expect(update).toHaveBeenCalledWith([1, 2], { mode: 'on', verified_flow: true }, undefined)
    expect(w.find('[data-testid="ticket-account-save"]').exists()).toBe(false); w.unmount()
  })
  it('单号读取脱敏配置，不自动保存或清空已有代理', async () => {
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { ids: [1] } }); await flushPromises()
    expect(get).toHaveBeenCalledWith(1, expect.any(AbortSignal)); expect(update).not.toHaveBeenCalled()
    expect(w.find('select').exists()).toBe(false)
    await save(w); await flushPromises()
    expect(update).not.toHaveBeenCalled()
    expect(w.emitted('saved')).toBeUndefined(); w.unmount()
  })
  it.each(['observe', 'off', 'recover_length'] as const)('关闭双链路恢复原守护选择：%s', async guard => {
    get.mockResolvedValue({ ...account(), verified_flow: true, watchdog_mode: guard, effective_watchdog_mode: 'recover' })
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { ids: [1] } }); await flushPromises()
    expect(guardSelect(w).props('modelValue')).toBe('recover')
    flow(w).vm.$emit('update:modelValue', 'false'); await flushPromises()
    expect(guardSelect(w).props('modelValue')).toBe(guard)
    await save(w); await flushPromises()
    expect(update.mock.calls[0][1]).toEqual({ verified_flow: false })
    w.unmount()
  })
  it('只勾选关闭批量双链路时不提交守护配置', async () => {
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { ids: [1, 2], bulk: true } }); await flushPromises()
    await w.get('[data-testid="ticket-edit-mode"]').setValue(true)
    await w.get('[data-testid="ticket-edit-flow"]').setValue(true)
    flow(w).vm.$emit('update:modelValue','false');await flushPromises()
    await save(w); await flushPromises()
    expect(update).toHaveBeenCalledWith([1, 2], { mode: 'on', verified_flow: false }, undefined)
    w.unmount()
  })
  it('批量全部默认未勾选，只提交选中项，保存后取消勾选', async () => {
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { ids: [1, 2], bulk: true } }); await flushPromises()
    expect(get).toHaveBeenCalledTimes(2); expect(w.find('[data-testid="ticket-account-save"]').exists()).toBe(false)
    await w.get('[data-testid="ticket-edit-mode"]').setValue(true)
    await w.get('[data-testid="ticket-master-toggle"]').trigger('click'); await flushPromises()
    await save(w); await flushPromises()
    expect(update).toHaveBeenCalledWith([1, 2], { mode: 'off' }, undefined)
    expect(w.find('[data-testid="ticket-account-save"]').exists()).toBe(false); w.unmount()
  })
  it('恢复继承必须明确选中，不把密码空白当作清除', async () => {
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { ids: [1, 2], bulk: true } }); await flushPromises()
    await w.get('[data-testid="ticket-edit-mode"]').setValue(true)
    await w.get('[data-testid="ticket-edit-proxy"]').setValue(true)
    w.findComponent(ProxyEditor).findAllComponents(Select)[0].vm.$emit('update:modelValue', 'dynamic'); await flushPromises()
    w.findComponent(ProxyEditor).findAllComponents(Select)[1].vm.$emit('update:modelValue', 'api'); await flushPromises()
    await expect(save(w)).rejects.toThrow(); expect(update).not.toHaveBeenCalled()
    w.findComponent(ProxyEditor).findAllComponents(Select)[0].vm.$emit('update:modelValue', 'inherit'); await flushPromises()
    await save(w); await flushPromises()
    expect(update).toHaveBeenCalledWith([1, 2], { mode: 'on', proxy_policy: { mode: 'inherit' } }, undefined); w.unmount()
  })
  it('代理保存后清空输入，切换账号不保留密码；加载失败禁止覆盖', async () => {
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { ids: [1] } }); await flushPromises()
    await w.get('[data-testid="ticket-edit-proxy"]').setValue(true)
    await w.get('[data-testid="ticket-proxy-url"]').setValue('http://user:synthetic@proxy.invalid:8080')
    await save(w); await flushPromises()
    expect((w.get('[data-testid="ticket-proxy-url"]').element as HTMLInputElement).value).toBe('')
    get.mockRejectedValueOnce(new Error('offline')); await w.setProps({ ids: [2] }); await flushPromises()
    expect(w.find('[data-testid="ticket-account-save"]').exists()).toBe(false); w.unmount()
  })
  it('账号支持0不限和独立缓存规则，不提交未勾选的批量项目', async () => {
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { ids: [1] } }); await flushPromises()
    await w.get('[data-testid="ticket-rule-max_attempts"]').setValue('0')
    await w.get('[data-testid="ticket-rule-cache_minutes"]').setValue('90')
    await save(w); await flushPromises()
    expect(update.mock.calls[0][1].rules).toMatchObject({ max_attempts: 0, cache_minutes: 90, target_length: 332 })
    w.unmount()
  })

  it.each([{ ids: [1] }, { draft: true }, { templateMode: true }])('单号入口关闭折叠，开启恢复规则与代理草稿：%s', async props => {
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props })
    await flushPromises()
    await w.get('[data-testid="ticket-rule-target_length"]').setValue('356')
    await w.get('[data-testid="ticket-edit-proxy"]').setValue(true)
    await w.get('[data-testid="ticket-proxy-url"]').setValue('http://user:synthetic@proxy.invalid:8080')
    await w.get('[data-testid="ticket-master-toggle"]').trigger('click')
    expect(w.get('[data-testid="ticket-workbench-body"]').isVisible()).toBe(false)
    expect((w.vm as unknown as { patch: () => unknown }).patch()).toEqual({ mode: 'off' })
    await w.get('[data-testid="ticket-master-toggle"]').trigger('click')
    await flushPromises()
    expect(w.get('[data-testid="ticket-workbench-body"]').isVisible()).toBe(true)
    expect((w.get('[data-testid="ticket-rule-target_length"]').element as HTMLInputElement).value).toBe('356')
    expect((w.get('[data-testid="ticket-proxy-url"]').element as HTMLInputElement).value).toContain('synthetic')
    expect(flow(w).exists()).toBe(true)
    expect(w.findAll('[role="switch"]')).toHaveLength(1)
    w.unmount()
  })

  it('批量总开关未选不提交，关闭只写开关，重开保持下层勾选草稿', async () => {
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { ids: [1, 2], bulk: true } })
    await flushPromises()
    expect((w.vm as unknown as { patch: () => unknown }).patch()).toEqual({})
    await w.get('[data-testid="ticket-edit-mode"]').setValue(true)
    expect(w.get('[data-testid="ticket-rule-target_length"]').attributes('disabled')).toBeDefined()
    await w.get('[data-testid="ticket-edit-target_length"]').setValue(true)
    await w.get('[data-testid="ticket-rule-target_length"]').setValue('356')
    await w.get('[data-testid="ticket-master-toggle"]').trigger('click')
    expect(w.get('[data-testid="ticket-workbench-body"]').isVisible()).toBe(false)
    expect((w.vm as unknown as { patch: () => unknown }).patch()).toEqual({ mode: 'off' })
    await w.get('[data-testid="ticket-master-toggle"]').trigger('click')
    expect((w.vm as unknown as { patch: () => unknown }).patch()).toEqual({ mode: 'on', rules: { target_length: 356 } })
    await w.get('[data-testid="ticket-edit-mode"]').setValue(false)
    expect(w.get('[data-testid="ticket-workbench-body"]').isVisible()).toBe(false)
    expect((w.vm as unknown as { patch: () => unknown }).patch()).toEqual({})
    w.unmount()
  })

  it('批量开关不同值保持空白，选择开启后才展开，不猜默认值', async () => {
    get.mockImplementation(async (id: number) => ({ ...account(), mode: id === 1 ? 'on' : 'off' }))
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { ids: [1, 2], bulk: true } })
    await flushPromises()
    await w.get('[data-testid="ticket-edit-mode"]').setValue(true)
    expect(w.get('[data-testid="ticket-workbench-body"]').isVisible()).toBe(false)
    await expect(save(w)).rejects.toThrow()
    w.findAllComponents(Select).find(c => c.attributes('data-testid') === 'ticket-mixed-mode')!.vm.$emit('update:modelValue', 'on')
    await flushPromises()
    expect(w.get('[data-testid="ticket-workbench-body"]').isVisible()).toBe(true)
    expect((w.vm as unknown as { patch: () => unknown }).patch()).toEqual({ mode: 'on' })
    w.unmount()
  })

  it('冻结保存快照，切换账号后不能继续写旧草稿', async () => {
    const w = mount(CodexTicketAccountSettings, { attachTo: document.body, props: { ids: [1] } })
    await flushPromises()
    await w.get('[data-testid="ticket-rule-target_length"]').setValue('356')
    const prepared = await (w.vm as unknown as { prepareSave: () => Promise<() => Promise<void>> }).prepareSave()
    await w.setProps({ ids: [2] })
    await flushPromises()
    await expect(prepared()).rejects.toThrow()
    expect(update).not.toHaveBeenCalled()
    w.unmount()
  })
})
