import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import CodexTicketSettings from '../CodexTicketSettings.vue'
import Select from '@/components/common/Select.vue'

const { get, put, showSuccess } = vi.hoisted(() => ({ get: vi.fn(), put: vi.fn(), showSuccess: vi.fn() }))
vi.mock('@/api/client', () => ({ apiClient: { get, put } }))
vi.mock('@/stores/app', () => ({ useAppStore: () => ({ showSuccess }) }))
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
const fresh = () => ({ enabled: false, proxy_configured: false, proxies: [], selection_mode: 'fixed', fixed_proxy_id: '', max_attempts: 3, retry_interval_seconds: 1, probe_interval_seconds: 60, revision: '' })
const existing = () => ({ ...fresh(), enabled: true, proxy_configured: true, proxies: [{ id: 'legacy', name: 'A', configured: true }], fixed_proxy_id: 'legacy', max_attempts: 1, revision: 'r1' })
const render = () => mount(CodexTicketSettings, { global: { stubs: {
  ConfirmDialog: { props: ['show'], emits: ['confirm', 'cancel'], template: '<div v-if="show"><button data-testid="confirm-remove" @click="$emit(\'confirm\')">confirm</button><button data-testid="cancel-remove" @click="$emit(\'cancel\')">cancel</button></div>' }
} } })

describe('CodexTicketSettings', () => {
  it('合格长度可自定义，尝试次数超过十仍原值提交', async () => {
    get.mockResolvedValue({ data: existing() }); const w = render(); await flushPromises()
    await w.get('#ticket-length').setValue('332'); await w.get('#ticket-attempts').setValue('200')
    expect(w.get('#ticket-attempts').attributes('max')).toBeUndefined()
    await w.get('[data-testid="codex-ticket-save"]').trigger('click'); await flushPromises()
    expect(put.mock.calls[0][1]).toMatchObject({ target_length: 332, max_attempts: 200 }); w.unmount()
  })
  beforeEach(() => {
    vi.clearAllMocks()
    get.mockResolvedValue({ data: fresh() })
    put.mockResolvedValue({ data: existing() })
  })
  it('默认关闭，不自动保存；新增代理提交后清空密码', async () => {
    const w = render()
    expect(w.get('button[role="switch"]').attributes('disabled')).toBeDefined()
    await flushPromises()
    expect(put).not.toHaveBeenCalled()
    await w.get('[data-testid="ticket-add"]').trigger('click')
    await w.get('button[role="switch"]').trigger('click')
    await w.get('input[type="password"]').setValue(' socks5h://user:secret@proxy:1080 ')
    await w.get('[data-testid="codex-ticket-save"]').trigger('click'); await flushPromises()
    const data = put.mock.calls[0][1]
    expect(data.enabled).toBe(true)
    expect(data.selection_mode).toBe('fixed')
    expect(data.proxies[0].harvest_proxy_url).toBe('socks5h://user:secret@proxy:1080')
    expect(data.fixed_proxy_id).toBe(data.proxies[0].id)
    expect(data.revision).toBe('')
    expect((w.get('input[type="password"]').element as HTMLInputElement).value).toBe('')
    expect(w.text()).not.toContain('secret')
    expect(showSuccess).toHaveBeenCalledOnce()
    w.unmount()
  })
  it('轮换由自研 Select 显式选择，已有地址留空保留，不自动提升旧重试频率', async () => {
    get.mockResolvedValue({ data: existing() })
    const w = render(); await flushPromises()
    expect((w.get('#ticket-attempts').element as HTMLInputElement).value).toBe('1')
    expect(w.find('select').exists()).toBe(false)
    await w.get('[data-testid="ticket-add"]').trigger('click')
    await w.findAll('input[type="password"]')[1].setValue('http://proxy-b:1080')
    w.findAllComponents(Select)[0].vm.$emit('update:modelValue', 'rotate'); await flushPromises()
    expect(w.find('#ticket-fixed').exists()).toBe(false)
    expect((w.get('#ticket-attempts').element as HTMLInputElement).value).toBe('3')
    await w.get('[data-testid="codex-ticket-save"]').trigger('click'); await flushPromises()
    const data = put.mock.calls[0][1]
    expect(data.selection_mode).toBe('rotate')
    expect(data.proxies[0]).toEqual({ id: 'legacy', name: 'A', harvest_proxy_url: '' })
    expect(data.proxies[1].harvest_proxy_url).toBe('http://proxy-b:1080')
    expect(data.max_attempts).toBe(3); expect(data.probe_interval_seconds).toBe(60)
    w.unmount()
  })
  it('加载失败禁止覆盖，重试可恢复；旧后端不假装支持新字段', async () => {
    get.mockRejectedValueOnce(new Error('offline'))
    const w = render(); await flushPromises()
    expect(w.get('[data-testid="codex-ticket-save"]').attributes('disabled')).toBeDefined()
    await w.findAll('button').find(b => b.text() === 'common.retry')!.trigger('click'); await flushPromises()
    expect(w.find('[role="alert"]').exists()).toBe(false)
    w.unmount()
    get.mockResolvedValueOnce({ data: { enabled: false, proxy_configured: false } })
    const legacy = render(); await flushPromises()
    expect(legacy.get('[data-testid="codex-ticket-save"]').attributes('disabled')).toBeDefined()
    expect(put).not.toHaveBeenCalled()
    legacy.unmount()
  })
  it('删除需要确认并保存才生效，保存中防重复，失败保留草稿', async () => {
    get.mockResolvedValue({ data: existing() })
    let reject!: (e: Error) => void
    put.mockImplementation(() => new Promise((_resolve, r) => { reject = r }))
    const w = render(); await flushPromises()
    await w.get('[data-testid="ticket-remove"]').trigger('click')
    await w.get('[data-testid="cancel-remove"]').trigger('click')
    expect(w.findAll('[data-testid="ticket-proxy-row"]')).toHaveLength(1)
    await w.get('[data-testid="ticket-remove"]').trigger('click')
    await w.get('[data-testid="confirm-remove"]').trigger('click')
    expect(w.findAll('[data-testid="ticket-proxy-row"]')).toHaveLength(0)
    expect(put).not.toHaveBeenCalled()
    await w.get('button[role="switch"]').trigger('click')
    await w.get('[data-testid="codex-ticket-save"]').trigger('click')
    await w.get('[data-testid="codex-ticket-save"]').trigger('click')
    expect(put).toHaveBeenCalledOnce()
    expect(put.mock.calls[0][1].proxies).toEqual([])
    reject(new Error('failed')); await flushPromises()
    expect(w.find('[role="alert"]').exists()).toBe(true)
    expect(showSuccess).not.toHaveBeenCalled()
    w.unmount()
  })
  it('不允许无代理启用或不合法重试参数', async () => {
    const w = render(); await flushPromises()
    await w.get('button[role="switch"]').trigger('click')
    await w.get('[data-testid="codex-ticket-save"]').trigger('click')
    expect(put).not.toHaveBeenCalled()
    await w.get('button[role="switch"]').trigger('click')
    await w.get('#ticket-attempts').setValue('0')
    await w.get('[data-testid="codex-ticket-save"]').trigger('click')
    expect(put).not.toHaveBeenCalled()
    w.unmount()
  })
})
